/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emulators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Bundled emulators the core can launch. */
        get: operations["listEmulators"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emulator/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Connect to a running emulator. 409 `ALREADY_CONNECTED` when connected, 502 `CONNECT_FAILED` when unreachable. */
        post: operations["connectEmulator"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emulator/launch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Start a bundled emulator on a free port, connect to it and, when
         *     `rom` is set, load the ROM. The emulator process is owned by the
         *     core: it is quit when the core shuts down.
         */
        post: operations["launchEmulator"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emulator/disconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Drop the connection; the emulator keeps running. Idempotent. */
        post: operations["disconnectEmulator"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emulator/rom": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Load a ROM by path on the emulator host. Clears scheduled units,
         *     refreshes the domain list and auto-selects the non-hidden domains.
         */
        post: operations["loadRom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emulator/close-rom": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["closeRom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emulator/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["pauseEmulator"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emulator/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resumeEmulator"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emulator/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resetEmulator"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emulator/step": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Pause (if running) and emulate `frames` frames. */
        post: operations["stepEmulator"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emulator/quit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Ask the emulator to exit. The core is disconnected afterwards. */
        post: operations["quitEmulator"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emulator/screenshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getScreenshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/domains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDomains"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/domains/selected": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Replace the selection used by generation. Unknown names are 400 `INVALID_ARGUMENT`. */
        put: operations["setSelectedDomains"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/domains/auto-select": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Select all non-hidden domains. */
        post: operations["autoSelectDomains"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/{domain}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domain: components["parameters"]["DomainName"];
            };
            cookie?: never;
        };
        get: operations["readMemory"];
        put: operations["writeMemory"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/{domain}/words": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domain: components["parameters"]["DomainName"];
            };
            cookie?: never;
        };
        /**
         * @description Raw 16-bit words for the memory visualizer. Returns every
         *     `stride`-th little-endian word of `[address, address+size)`, in
         *     memory order and byte order: word i is the 2 bytes at
         *     `address + 2*stride*i`. The response has
         *     `2*ceil(floor(size/2)/stride)` bytes; a trailing odd byte is
         *     ignored. The range must lie inside the domain (400
         *     `OUT_OF_RANGE`); there is no 64 KiB cap. The core reads the
         *     emulator in batches of at most 1 MiB.
         */
        get: operations["readMemoryWords"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * @description Deep merge: only the given fields change, nested objects are merged
         *     field by field. The result is validated as a whole (400
         *     `INVALID_ARGUMENT`, nothing changes) and persisted to
         *     `settings.json`. `autoCorrupt` is not persisted; it is false at
         *     start.
         */
        patch: operations["patchSettings"];
        trace?: never;
    };
    "/blast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Generate a layer with the current settings on the selected domains and apply it (no backup). 409 `NO_ROM` without a ROM, 400 `INVALID_ARGUMENT` when no domain is selected. */
        post: operations["manualBlast"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blast/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Apply a layer to the running game. With `backup`, the current bytes at every unit are stored for `/blast/toggle`. */
        post: operations["applyLayer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blast/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listUnits"];
        put?: never;
        post?: never;
        delete: operations["clearUnits"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blast/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description BlastLayer ON/OFF. `on:false` clears scheduled units and applies the
         *     uncorrupt backup; `on:true` re-applies the last layer applied with
         *     backup. 409 `NO_BACKUP` if no layer was applied with backup.
         */
        post: operations["toggleLayer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blast/reroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Return a rerolled copy of the layer following the `reroll` settings. Locked units are unchanged. */
        post: operations["rerollLayer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/savestates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSavestates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/savestates/{slot}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slot: components["parameters"]["Slot"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Save the current state into the slot, replacing its content. Creates a stash key with `parentKey == key` (not added to the stash history). The label is kept. */
        post: operations["saveSavestate"];
        /** @description Empty the slot (key and label). */
        delete: operations["deleteSavestate"];
        options?: never;
        head?: never;
        patch: operations["patchSavestate"];
        trace?: never;
    };
    "/savestates/{slot}/load": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slot: components["parameters"]["Slot"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Clear scheduled units and load the slot's state. 404 `NOT_FOUND` for an empty slot. */
        post: operations["loadSavestate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listStash"];
        put?: never;
        post?: never;
        delete: operations["clearStash"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stash/corrupt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Clear units, optionally load the slot's state, generate a layer with
         *     the current settings, apply it with backup and add a new key
         *     (`parentKey` = the slot's key) to the stash history.
         */
        post: operations["corruptStash"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stash/inject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Apply the layer of `key` (stash or stockpile) on the slot's state; adds a new stash key with the slot's `parentKey`. */
        post: operations["injectStash"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stash/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Concatenate the layers of 2+ keys (stash or stockpile; duplicates removed) on the first key's state, run it and add a new stash key. */
        post: operations["mergeStash"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stash/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: components["parameters"]["Key"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteStashKey"];
        options?: never;
        head?: never;
        patch: operations["patchStashKey"];
        trace?: never;
    };
    "/stash/{key}/run": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: components["parameters"]["Key"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Clear units, load the key's state and apply its layer with backup. */
        post: operations["runStashKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stash/{key}/original": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: components["parameters"]["Key"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Clear units and load the key's state without its layer. */
        post: operations["originalStashKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stash/{key}/reroll": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: components["parameters"]["Key"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Add a new stash key with a rerolled copy of the layer (same `parentKey`) and run it. */
        post: operations["rerollStashKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stash/{key}/to-stockpile": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: components["parameters"]["Key"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Move the key from the stash history to the end of the stockpile. */
        post: operations["stashKeyToStockpile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stash/{key}/layer": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: components["parameters"]["Key"];
            };
            cookie?: never;
        };
        get: operations["getStashLayer"];
        put: operations["putStashLayer"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stockpile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listStockpile"];
        put?: never;
        post?: never;
        delete: operations["clearStockpile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stockpile/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description New order. `keys` must be a permutation of the stockpile's keys (400 otherwise). */
        post: operations["reorderStockpile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stockpile/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The stockpile as an `.sks` zip (`stockpile.json`, `states/<parentKey>.state`, `lists/<name>.txt` for lists referenced by units). */
        get: operations["exportStockpile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stockpile/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Upload an `.sks`. Replaces the stockpile unless `merge=true`, which appends. */
        post: operations["importStockpile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stockpile/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Write the stockpile as `.sks` to a path on the core host. */
        post: operations["saveStockpile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stockpile/load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Replace the stockpile with an `.sks` at a path on the core host. */
        post: operations["loadStockpile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stockpile/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: components["parameters"]["Key"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteStockpileKey"];
        options?: never;
        head?: never;
        patch: operations["patchStockpileKey"];
        trace?: never;
    };
    "/stockpile/{key}/run": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: components["parameters"]["Key"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Clear units, load the key's state and apply its layer with backup. */
        post: operations["runStockpileKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stockpile/{key}/layer": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: components["parameters"]["Key"];
            };
            cookie?: never;
        };
        get: operations["getStockpileLayer"];
        put: operations["putStockpileLayer"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/protection/backup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Take a game protection backup now (savestate kept in memory, at most `gameProtection.keep`). */
        post: operations["protectionBackup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/protection/back": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Load the most recent backup and drop it. 409 `NO_BACKUP` when there is none. */
        post: operations["protectionBack"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/protection/last": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Load the most recent backup without dropping it, so the same state
         *     can be reloaded repeatedly. 409 `NO_BACKUP` when there is none.
         */
        post: operations["protectionLast"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/browse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description List a directory on the core host for the ROM picker: directories
         *     first, then files with an extension melonDS opens (`.nds`, `.srl`,
         *     `.dsi`, `.ids`, those plus `.zst`, and archives), each group sorted
         *     case-insensitively. Hidden (dot-prefixed) entries are omitted.
         *     Without `path`, lists the user's home directory (or the data
         *     directory). On Windows, a drive root lists the other drives as
         *     directory entries. 400 `INVALID_ARGUMENT` when `path` is not a
         *     directory, 404 `NOT_FOUND` when it does not exist, 403
         *     `PERMISSION_DENIED` when it cannot be read.
         */
        get: operations["browse"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listLists"];
        put?: never;
        /**
         * @description Upload a list file (one hex value per line). The list name is `name`
         *     or the file name without `.txt`; an existing list is replaced.
         *     400 for an empty or malformed list.
         */
        post: operations["uploadList"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lists/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteList"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Server-Sent Events. Each event is `event: <type>` + `data: <json>`.
         *     A `status` event is always sent first.
         *
         *     | type | data |
         *     |---|---|
         *     | `status` | `Status`, on connect and on every change |
         *     | `frame` | `FrameEvent`, at most 10 per second |
         *     | `blast` | `BlastEvent`, after every generated layer has been applied (manual, auto-corrupt, GH corrupt) |
         *     | `stash`, `stockpile`, `savestates`, `settings`, `domains`, `lists` | `ChangedEvent` (`{}`): refetch |
         *     | `log` | `LogEvent` |
         */
        get: operations["streamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @description Human-readable message. */
            error: string;
            /** @description Machine-readable code (see the API description). */
            code: string;
        };
        Status: {
            /** @description Core version. */
            version: string;
            dataDir: string;
            connected: boolean;
            /** @description The connected emulator did not answer a call in time. Operations fail with `EMULATOR_UNRESPONSIVE` until a ping succeeds; disconnect and quit still work. */
            unresponsive: boolean;
            /** @description Emulator API address; empty when disconnected. */
            address: string;
            /** @description Present while connected. */
            emulator?: components["schemas"]["EmulatorInfo"];
            /** @description Present while connected (state `noRom` without a ROM). */
            game?: components["schemas"]["GameStatus"];
            /** @description Number of game protection backups held. */
            protectionBackups: number;
            blastLayer: components["schemas"]["BlastLayerState"];
            /** @description The core operation currently running, if any. */
            busy?: components["schemas"]["BusyStatus"];
        };
        BusyStatus: {
            /**
             * @description Operation name, e.g. `loadRom`, `blast`, `protectionBackup`.
             * @example loadRom
             */
            operation: string;
            /**
             * Format: int64
             * @description Milliseconds the operation has been running.
             */
            sinceMs: number;
        };
        BlastLayerState: {
            /** @description A layer was applied with backup, so it can be toggled. */
            available: boolean;
            on: boolean;
        };
        EmulatorInfo: {
            /** @example melonDS */
            name: string;
            version: string;
            /** @example nds */
            system: string;
            protocolVersion: number;
            capabilities: components["schemas"]["Capabilities"];
        };
        Capabilities: {
            savestates: boolean;
            screenshot: boolean;
            input: boolean;
            loadRom: boolean;
            reset: boolean;
            /** Format: int64 */
            maxPayload: number;
        };
        /** @enum {string} */
        GameState: "noRom" | "running" | "paused";
        GameStatus: {
            state: components["schemas"]["GameState"];
            /** Format: int64 */
            frame: number;
            romPath: string;
            title: string;
            code: string;
            console: string;
        };
        DirListing: {
            /** @description Absolute, cleaned path of the listed directory. */
            path: string;
            /** @description Absolute path of the parent directory; null at a filesystem root. */
            parent: string | null;
            entries: components["schemas"]["DirEntry"][];
        };
        DirEntry: {
            name: string;
            /** @description Absolute path of the entry. */
            path: string;
            dir: boolean;
            /**
             * Format: int64
             * @description File size in bytes; 0 for directories.
             */
            size: number;
        };
        BundledEmulator: {
            name: string;
            path: string;
            /** @description The executable exists. */
            present: boolean;
        };
        ConnectRequest: {
            /** @example 127.0.0.1:42069 */
            address: string;
        };
        LaunchRequest: {
            name: string;
            /** @description ROM path to load after connecting. */
            rom?: string;
        };
        PathRequest: {
            path: string;
        };
        StepRequest: {
            frames: number;
        };
        Domain: {
            name: string;
            /** Format: int64 */
            size: number;
            wordSize: number;
            bigEndian: boolean;
            writable: boolean;
            hidden: boolean;
            selected: boolean;
        };
        NamesRequest: {
            names: string[];
        };
        /** @description Bytes as hex, lowercase in responses. */
        Hex: string;
        /** @description Integer as a decimal string (may exceed 2^53). */
        Decimal: string;
        MemoryChunk: {
            domain: string;
            /** Format: int64 */
            address: number;
            data: components["schemas"]["Hex"];
        };
        MemoryWrite: {
            /** Format: int64 */
            address: number;
            data: components["schemas"]["Hex"];
        };
        /** @enum {string} */
        Engine: "nightmare" | "hellgenie" | "distortion" | "freeze" | "pipe" | "vector" | "cluster" | "custom";
        /** @enum {string} */
        BlastRadius: "spread" | "chunk" | "burst" | "normalized" | "proportional" | "even";
        /**
         * @description Bytes per unit (8/16/32/64-bit).
         * @enum {integer}
         */
        Precision: 1 | 2 | 4 | 8;
        /** @enum {string} */
        NightmareAlgo: "random" | "randomTilt" | "tilt";
        /** @enum {string} */
        ClusterMethod: "random" | "reverse" | "rotateForwards" | "rotateBackwards" | "overwrite";
        /** @enum {string} */
        ClusterDirection: "forwards" | "backwards";
        /** @enum {string} */
        UnitSource: "value" | "store";
        /** @enum {string} */
        CustomValueSource: "random" | "valueList" | "range";
        /** @enum {string} */
        CustomStoreAddress: "same" | "random";
        /** @enum {string} */
        StoreTime: "immediate" | "preexecute";
        /** @enum {string} */
        StoreType: "once" | "continuous";
        /**
         * @description Only generation-time limiter checks are supported.
         * @enum {string}
         */
        LimiterTime: "none" | "generate";
        ValueRange: {
            /** @description Unsigned decimal. */
            min: string;
            /** @description Unsigned decimal; min <= max < 2^(8*precision). */
            max: string;
        };
        /**
         * @description Min/max per precision (bytes). Default full range, e.g.
         *     `"1": {"min": "0", "max": "255"}`.
         */
        PrecisionRanges: {
            1: components["schemas"]["ValueRange"];
            2: components["schemas"]["ValueRange"];
            4: components["schemas"]["ValueRange"];
            8: components["schemas"]["ValueRange"];
        };
        NightmareSettings: {
            algo: components["schemas"]["NightmareAlgo"];
            ranges: components["schemas"]["PrecisionRanges"];
        };
        HellgenieSettings: {
            ranges: components["schemas"]["PrecisionRanges"];
        };
        DistortionSettings: {
            /** @description Frames. Default 50. */
            delay: number;
        };
        VectorSettings: {
            /** @description List name; empty = none. */
            limiterList: string;
            valueList: string;
            unlockPrecision: boolean;
        };
        ClusterSettings: {
            limiterList: string;
            /** @description Default 3. */
            chunkSize: number;
            method: components["schemas"]["ClusterMethod"];
            /** @description Rotation amount. Default 1. */
            modifier: number;
            direction: components["schemas"]["ClusterDirection"];
            /** @description One unit per element (RTCV MULTIOUT). Default true. */
            splitUnits: boolean;
            filterAll: boolean;
        };
        CustomSettings: {
            source: components["schemas"]["UnitSource"];
            valueSource: components["schemas"]["CustomValueSource"];
            ranges: components["schemas"]["PrecisionRanges"];
            valueList: string;
            storeAddress: components["schemas"]["CustomStoreAddress"];
            storeTime: components["schemas"]["StoreTime"];
            storeType: components["schemas"]["StoreType"];
            tilt: components["schemas"]["Decimal"];
            delay: number;
            /** @description 0 = infinite. */
            lifetime: number;
            loop: boolean;
            limiterList: string;
            limiterTime: components["schemas"]["LimiterTime"];
            limiterInverted: boolean;
        };
        RerollSettings: {
            /** @description Re-randomize the address. Default false. */
            address: boolean;
            /** @description Re-randomize a store unit's source address. Default true. */
            sourceAddress: boolean;
            /** @description Re-randomize the domain. Default false. */
            domain: boolean;
            /** @description Re-randomize a store unit's source domain. Default true. */
            sourceDomain: boolean;
            /** @description Values follow the custom engine range/list. Default false. */
            followCustomEngine: boolean;
        };
        GameProtectionSettings: {
            enabled: boolean;
            /** @description Default 5. */
            intervalSeconds: number;
            /** @description Backups kept. Default 10. */
            keep: number;
        };
        /**
         * @description Defaults: nightmare, intensity 1, errorDelay 1, spread, precision 1,
         *     alignment 0, autoCorrupt false, maxInfiniteUnits 50, lockUnits
         *     false; engine parameters as in RTCV (full min/max ranges).
         */
        Settings: {
            engine: components["schemas"]["Engine"];
            /** Format: int64 */
            intensity: number;
            /**
             * Format: int64
             * @description Frames between auto-corrupt blasts.
             */
            errorDelay: number;
            radius: components["schemas"]["BlastRadius"];
            precision: components["schemas"]["Precision"];
            /** @description 0..precision-1. */
            alignment: number;
            autoCorrupt: boolean;
            maxInfiniteUnits: number;
            lockUnits: boolean;
            nightmare: components["schemas"]["NightmareSettings"];
            hellgenie: components["schemas"]["HellgenieSettings"];
            distortion: components["schemas"]["DistortionSettings"];
            vector: components["schemas"]["VectorSettings"];
            cluster: components["schemas"]["ClusterSettings"];
            custom: components["schemas"]["CustomSettings"];
            reroll: components["schemas"]["RerollSettings"];
            gameProtection: components["schemas"]["GameProtectionSettings"];
        };
        PrecisionRangesPatch: {
            1?: components["schemas"]["ValueRange"];
            2?: components["schemas"]["ValueRange"];
            4?: components["schemas"]["ValueRange"];
            8?: components["schemas"]["ValueRange"];
        };
        NightmareSettingsPatch: {
            algo?: components["schemas"]["NightmareAlgo"];
            ranges?: components["schemas"]["PrecisionRangesPatch"];
        };
        HellgenieSettingsPatch: {
            ranges?: components["schemas"]["PrecisionRangesPatch"];
        };
        DistortionSettingsPatch: {
            delay?: number;
        };
        VectorSettingsPatch: {
            limiterList?: string;
            valueList?: string;
            unlockPrecision?: boolean;
        };
        ClusterSettingsPatch: {
            limiterList?: string;
            chunkSize?: number;
            method?: components["schemas"]["ClusterMethod"];
            modifier?: number;
            direction?: components["schemas"]["ClusterDirection"];
            splitUnits?: boolean;
            filterAll?: boolean;
        };
        CustomSettingsPatch: {
            source?: components["schemas"]["UnitSource"];
            valueSource?: components["schemas"]["CustomValueSource"];
            ranges?: components["schemas"]["PrecisionRangesPatch"];
            valueList?: string;
            storeAddress?: components["schemas"]["CustomStoreAddress"];
            storeTime?: components["schemas"]["StoreTime"];
            storeType?: components["schemas"]["StoreType"];
            tilt?: components["schemas"]["Decimal"];
            delay?: number;
            lifetime?: number;
            loop?: boolean;
            limiterList?: string;
            limiterTime?: components["schemas"]["LimiterTime"];
            limiterInverted?: boolean;
        };
        RerollSettingsPatch: {
            address?: boolean;
            sourceAddress?: boolean;
            domain?: boolean;
            sourceDomain?: boolean;
            followCustomEngine?: boolean;
        };
        GameProtectionSettingsPatch: {
            enabled?: boolean;
            intervalSeconds?: number;
            keep?: number;
        };
        /** @description Any subset of `Settings`; nested objects are merged. */
        SettingsPatch: {
            engine?: components["schemas"]["Engine"];
            /** Format: int64 */
            intensity?: number;
            /** Format: int64 */
            errorDelay?: number;
            radius?: components["schemas"]["BlastRadius"];
            precision?: components["schemas"]["Precision"];
            alignment?: number;
            autoCorrupt?: boolean;
            maxInfiniteUnits?: number;
            lockUnits?: boolean;
            nightmare?: components["schemas"]["NightmareSettingsPatch"];
            hellgenie?: components["schemas"]["HellgenieSettingsPatch"];
            distortion?: components["schemas"]["DistortionSettingsPatch"];
            vector?: components["schemas"]["VectorSettingsPatch"];
            cluster?: components["schemas"]["ClusterSettingsPatch"];
            custom?: components["schemas"]["CustomSettingsPatch"];
            reroll?: components["schemas"]["RerollSettingsPatch"];
            gameProtection?: components["schemas"]["GameProtectionSettingsPatch"];
        };
        /**
         * @description RTCV BlastUnit. `value` is `precision` bytes for `source: value`
         *     (empty for store units). `tilt` is added to the value with
         *     wrap-around arithmetic on `precision` bytes.
         */
        Unit: {
            enabled: boolean;
            locked: boolean;
            bigEndian: boolean;
            domain: string;
            /** Format: int64 */
            address: number;
            precision: number;
            source: components["schemas"]["UnitSource"];
            value: components["schemas"]["Hex"];
            sourceDomain: string;
            /** Format: int64 */
            sourceAddress: number;
            storeTime: components["schemas"]["StoreTime"];
            storeType: components["schemas"]["StoreType"];
            tilt: components["schemas"]["Decimal"];
            executeFrame: number;
            /** @description Frames; 0 = infinite. */
            lifetime: number;
            loop: boolean;
            /** @description Delay for each loop re-apply; null uses executeFrame. */
            loopTiming?: number | null;
            limiterTime: components["schemas"]["LimiterTime"];
            limiterList: string;
            invertLimiter: boolean;
            generatedUsingValueList: boolean;
            note: string;
        };
        /** @description A blast layer. `.bl` files are this object. */
        Layer: {
            note: string;
            units: components["schemas"]["Unit"][];
        };
        LayerRequest: {
            layer: components["schemas"]["Layer"];
        };
        ApplyRequest: {
            layer: components["schemas"]["Layer"];
            backup: boolean;
        };
        ToggleRequest: {
            on: boolean;
        };
        EmuStoreSource: {
            domain: string;
            /** Format: int64 */
            address: number;
            continuous: boolean;
        };
        /** @description A unit scheduled in the emulator (emulator API `Unit`). Exactly one of `value` and `store` is set. */
        EmuUnit: {
            /** Format: int64 */
            id: number;
            domain: string;
            /** Format: int64 */
            address: number;
            /** Format: int64 */
            size: number;
            value?: components["schemas"]["Hex"];
            store?: components["schemas"]["EmuStoreSource"];
            /** Format: int64 */
            tilt: number;
            /** Format: int64 */
            delay: number;
            /** Format: int64 */
            lifetime: number;
            loop: boolean;
            /** Format: int64 */
            loopDelay: number;
        };
        GameInfo: {
            title: string;
            code: string;
            romPath: string;
            system: string;
        };
        StashKey: {
            key: string;
            /** @description Key of the savestate this key is based on (`states/<parentKey>.state`). */
            parentKey: string;
            /** @description Display name; defaults to `key`. */
            alias: string;
            note: string;
            game: components["schemas"]["GameInfo"];
            selectedDomains: string[];
            /** @description Number of units in the layer. */
            unitCount: number;
            layer?: components["schemas"]["Layer"];
            /** Format: date-time */
            createdAt: string;
        };
        StashKeyPatch: {
            alias?: string;
            note?: string;
        };
        SavestateSlot: {
            slot: number;
            /** @description Savestate key; absent for an empty slot. */
            key?: string;
            label: string;
            game?: components["schemas"]["GameInfo"];
        };
        LabelRequest: {
            label: string;
        };
        CorruptRequest: {
            slot: number;
            /** @description Load the slot's state before generating (RTCV Auto-Load State). */
            loadBefore: boolean;
        };
        InjectRequest: {
            key: string;
            slot: number;
        };
        KeysRequest: {
            keys: string[];
        };
        ToStockpileRequest: {
            /** @description New display name. */
            alias?: string;
        };
        FileUpload: {
            /** Format: binary */
            file: string;
        };
        ListInfo: {
            name: string;
            /** @description Bytes per entry (length of the first entry). */
            precision: number;
            entries: number;
        };
        ListUpload: {
            /** Format: binary */
            file: string;
            name?: string;
        };
        /** @enum {string} */
        EventType: "status" | "frame" | "blast" | "stash" | "stockpile" | "savestates" | "settings" | "domains" | "lists" | "log";
        FrameEvent: {
            /** Format: int64 */
            frame: number;
        };
        BlastEvent: {
            /** @description Units in the generated layer. */
            count: number;
            engine: components["schemas"]["Engine"];
            /** Format: double */
            elapsedMs: number;
        };
        /** @description Empty object: refetch the resource named by the event type. */
        ChangedEvent: Record<string, never>;
        /** @enum {string} */
        LogLevel: "debug" | "info" | "warn" | "error";
        LogEvent: {
            level: components["schemas"]["LogLevel"];
            msg: string;
        };
    };
    responses: {
        /** @description Error. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        DomainName: string;
        Slot: number;
        Key: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Core and emulator status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listEmulators: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bundled emulators. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BundledEmulator"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    connectEmulator: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectRequest"];
            };
        };
        responses: {
            /** @description Connected. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    launchEmulator: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LaunchRequest"];
            };
        };
        responses: {
            /** @description Launched and connected. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    disconnectEmulator: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Disconnected. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    loadRom: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PathRequest"];
            };
        };
        responses: {
            /** @description ROM loaded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameStatus"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    closeRom: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ROM closed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameStatus"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    pauseEmulator: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paused. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameStatus"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    resumeEmulator: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Running. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameStatus"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    resetEmulator: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reset. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameStatus"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    stepEmulator: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StepRequest"];
            };
        };
        responses: {
            /** @description Stepped; the emulator is paused. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameStatus"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    quitEmulator: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Quit sent. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    getScreenshot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PNG of all screens stacked vertically. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listDomains: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Memory domains of the loaded game (empty without a ROM). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Domain"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    setSelectedDomains: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NamesRequest"];
            };
        };
        responses: {
            /** @description Updated domain list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Domain"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    autoSelectDomains: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated domain list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Domain"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    readMemory: {
        parameters: {
            query: {
                address: number;
                size: number;
            };
            header?: never;
            path: {
                domain: components["parameters"]["DomainName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Memory contents. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryChunk"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    writeMemory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domain: components["parameters"]["DomainName"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryWrite"];
            };
        };
        responses: {
            /** @description Written. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    readMemoryWords: {
        parameters: {
            query: {
                address?: number;
                size: number;
                stride?: number;
            };
            header?: never;
            path: {
                domain: components["parameters"]["DomainName"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sampled words, little-endian, 2 bytes each. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The whole settings object. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    patchSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsPatch"];
            };
        };
        responses: {
            /** @description The whole settings object after the update. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    manualBlast: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The generated layer. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Layer"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    applyLayer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyRequest"];
            };
        };
        responses: {
            /** @description Applied. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    listUnits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Units currently scheduled in the emulator. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmuUnit"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    clearUnits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cleared. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    toggleLayer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToggleRequest"];
            };
        };
        responses: {
            /** @description Toggled. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    rerollLayer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LayerRequest"];
            };
        };
        responses: {
            /** @description The rerolled layer. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Layer"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listSavestates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All savestate slots, numbered 1..50, in order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavestateSlot"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    saveSavestate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slot: components["parameters"]["Slot"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The slot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavestateSlot"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteSavestate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slot: components["parameters"]["Slot"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    patchSavestate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slot: components["parameters"]["Slot"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LabelRequest"];
            };
        };
        responses: {
            /** @description The slot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavestateSlot"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    loadSavestate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slot: components["parameters"]["Slot"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Loaded. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    listStash: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stash history, oldest first. `layer` is omitted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StashKey"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    clearStash: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cleared. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    corruptStash: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorruptRequest"];
            };
        };
        responses: {
            /** @description The new key, with `layer`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StashKey"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    injectStash: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InjectRequest"];
            };
        };
        responses: {
            /** @description The new key, with `layer`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StashKey"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    mergeStash: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeysRequest"];
            };
        };
        responses: {
            /** @description The new key, with `layer`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StashKey"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteStashKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: components["parameters"]["Key"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    patchStashKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: components["parameters"]["Key"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StashKeyPatch"];
            };
        };
        responses: {
            /** @description The key without `layer`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StashKey"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    runStashKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: components["parameters"]["Key"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Running. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    originalStashKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: components["parameters"]["Key"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Loaded. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    rerollStashKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: components["parameters"]["Key"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The new key, with `layer`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StashKey"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    stashKeyToStockpile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: components["parameters"]["Key"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ToStockpileRequest"];
            };
        };
        responses: {
            /** @description The key as stored in the stockpile, without `layer`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StashKey"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getStashLayer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: components["parameters"]["Key"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The key's layer. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Layer"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    putStashLayer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: components["parameters"]["Key"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Layer"];
            };
        };
        responses: {
            /** @description The stored layer. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Layer"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listStockpile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stockpile in order. `layer` is omitted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StashKey"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    clearStockpile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cleared. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    reorderStockpile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeysRequest"];
            };
        };
        responses: {
            /** @description Stockpile in the new order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StashKey"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    exportStockpile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The `.sks` file. */
            200: {
                headers: {
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/zip": string;
                };
            };
            default: components["responses"]["Error"];
        };
    };
    importStockpile: {
        parameters: {
            query?: {
                merge?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["FileUpload"];
            };
        };
        responses: {
            /** @description The stockpile after import. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StashKey"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    saveStockpile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PathRequest"];
            };
        };
        responses: {
            /** @description Saved. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    loadStockpile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PathRequest"];
            };
        };
        responses: {
            /** @description The loaded stockpile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StashKey"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteStockpileKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: components["parameters"]["Key"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    patchStockpileKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: components["parameters"]["Key"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StashKeyPatch"];
            };
        };
        responses: {
            /** @description The key without `layer`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StashKey"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    runStockpileKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: components["parameters"]["Key"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Running. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    getStockpileLayer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: components["parameters"]["Key"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The key's layer. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Layer"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    putStockpileLayer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: components["parameters"]["Key"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Layer"];
            };
        };
        responses: {
            /** @description The stored layer. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Layer"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    protectionBackup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backed up. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    protectionBack: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Loaded. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    protectionLast: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Loaded. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    browse: {
        parameters: {
            query?: {
                path?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Directory listing. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirListing"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listLists: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lists in `data/lists/*.txt`, sorted by name. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListInfo"][];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    uploadList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["ListUpload"];
            };
        };
        responses: {
            /** @description The stored list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListInfo"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    streamEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
