import type { components } from './schema'

type S = components['schemas']

export type ApiErrorBody = S['Error']
export type Status = S['Status']
export type BusyStatus = S['BusyStatus']
export type GameStatus = S['GameStatus']
export type BundledEmulator = S['BundledEmulator']
export type Domain = S['Domain']
export type Settings = S['Settings']
export type SettingsPatch = S['SettingsPatch']
export type Engine = S['Engine']
export type Precision = S['Precision']
export type PrecisionRanges = S['PrecisionRanges']
export type Unit = S['Unit']
export type Layer = S['Layer']
export type EmuUnit = S['EmuUnit']
export type FreezeMode = S['FreezeMode']
export type Capabilities = S['Capabilities']
export type StashKey = S['StashKey']
export type SavestateSlot = S['SavestateSlot']
export type ListInfo = S['ListInfo']
export type FrameEvent = S['FrameEvent']
export type BlastEvent = S['BlastEvent']
export type LogEvent = S['LogEvent']
export type UnitsEvent = S['UnitsEvent']
export type LogLevel = S['LogLevel']
export type EventType = S['EventType']
export type MemoryChunk = S['MemoryChunk']
export type DirListing = S['DirListing']
export type DirEntry = S['DirEntry']
