/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.2 */

#ifndef PB_RTCVISH_EMULATOR_V1_EMULATOR_PB_H_INCLUDED
#define PB_RTCVISH_EMULATOR_V1_EMULATOR_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* FRAME writes once per frame before emulation (RTCV's behaviour).
 SCANLINE also rewrites at every scanline, so a value the game
 overwrites is restored within a fraction of a frame. HARD, for value
 units only, additionally intercepts CPU and DMA writes to the unit's
 bytes so the game never observes another value. Emulators that cannot
 implement a mode fall back to the previous one and say so in
 Capabilities. */
typedef enum _rtcvish_emulator_v1_Mode {
    rtcvish_emulator_v1_Mode_FRAME = 0,
    rtcvish_emulator_v1_Mode_SCANLINE = 1,
    rtcvish_emulator_v1_Mode_HARD = 2
} rtcvish_emulator_v1_Mode;

typedef enum _rtcvish_emulator_v1_Error_Code {
    rtcvish_emulator_v1_Error_Code_UNKNOWN = 0,
    rtcvish_emulator_v1_Error_Code_INVALID_ARGUMENT = 1,
    rtcvish_emulator_v1_Error_Code_NOT_FOUND = 2,
    rtcvish_emulator_v1_Error_Code_OUT_OF_RANGE = 3,
    rtcvish_emulator_v1_Error_Code_NO_ROM = 4,
    rtcvish_emulator_v1_Error_Code_UNSUPPORTED = 5,
    rtcvish_emulator_v1_Error_Code_FAILED = 6,
    rtcvish_emulator_v1_Error_Code_BUSY = 7
} rtcvish_emulator_v1_Error_Code;

typedef enum _rtcvish_emulator_v1_Status_State {
    rtcvish_emulator_v1_Status_State_NO_ROM = 0,
    rtcvish_emulator_v1_Status_State_RUNNING = 1,
    rtcvish_emulator_v1_Status_State_PAUSED = 2
} rtcvish_emulator_v1_Status_State;

/* Struct definitions */
typedef struct _rtcvish_emulator_v1_Error {
    rtcvish_emulator_v1_Error_Code code;
    char *message;
} rtcvish_emulator_v1_Error;

/* Handshake. Must be the first request on a connection. */
typedef struct _rtcvish_emulator_v1_HelloRequest {
    uint32_t protocol_version;
    char *client_name;
} rtcvish_emulator_v1_HelloRequest;

typedef struct _rtcvish_emulator_v1_Capabilities {
    bool savestates;
    bool screenshot;
    bool input;
    bool load_rom;
    bool reset;
    /* Largest read/write/savestate payload the emulator accepts in one message. */
    uint32_t max_payload;
    /* Unit modes beyond FRAME the emulator implements. */
    bool scanline_units;
    bool hard_units;
} rtcvish_emulator_v1_Capabilities;

typedef struct _rtcvish_emulator_v1_HelloResponse {
    uint32_t protocol_version;
    char *emulator; /* e.g. "melonDS" */
    char *version; /* emulator version string */
    char *system; /* e.g. "nds" */
    bool has_capabilities;
    rtcvish_emulator_v1_Capabilities capabilities;
} rtcvish_emulator_v1_HelloResponse;

typedef struct _rtcvish_emulator_v1_Status {
    rtcvish_emulator_v1_Status_State state;
    /* Frames emulated since the ROM was loaded. Monotonic; savestate loads
 do not rewind it. */
    uint64_t frame;
    char *rom_path;
    char *game_title;
    char *game_code;
    char *console; /* e.g. "DS", "DSi" */
} rtcvish_emulator_v1_Status;

typedef struct _rtcvish_emulator_v1_GetStatusRequest {
    char dummy_field;
} rtcvish_emulator_v1_GetStatusRequest;

typedef struct _rtcvish_emulator_v1_GetStatusResponse {
    bool has_status;
    rtcvish_emulator_v1_Status status;
} rtcvish_emulator_v1_GetStatusResponse;

typedef struct _rtcvish_emulator_v1_Domain {
    char *name;
    uint64_t size;
    uint32_t word_size;
    bool big_endian;
    bool writable;
    /* True for domains RTCV blacklisted by default (not selected for
 corruption unless the user opts in). */
    bool hidden;
} rtcvish_emulator_v1_Domain;

typedef struct _rtcvish_emulator_v1_ListDomainsRequest {
    char dummy_field;
} rtcvish_emulator_v1_ListDomainsRequest;

typedef struct _rtcvish_emulator_v1_ListDomainsResponse {
    pb_size_t domains_count;
    struct _rtcvish_emulator_v1_Domain *domains;
} rtcvish_emulator_v1_ListDomainsResponse;

typedef struct _rtcvish_emulator_v1_Range {
    char *domain;
    uint64_t address;
    uint32_t size;
} rtcvish_emulator_v1_Range;

typedef struct _rtcvish_emulator_v1_ReadRequest {
    pb_size_t ranges_count;
    struct _rtcvish_emulator_v1_Range *ranges;
} rtcvish_emulator_v1_ReadRequest;

/* One entry per requested range, in order. */
typedef struct _rtcvish_emulator_v1_ReadResponse {
    pb_size_t data_count;
    pb_bytes_array_t **data;
} rtcvish_emulator_v1_ReadResponse;

typedef struct _rtcvish_emulator_v1_WriteChunk {
    char *domain;
    uint64_t address;
    pb_bytes_array_t *data;
} rtcvish_emulator_v1_WriteChunk;

typedef struct _rtcvish_emulator_v1_WriteRequest {
    pb_size_t chunks_count;
    struct _rtcvish_emulator_v1_WriteChunk *chunks;
} rtcvish_emulator_v1_WriteRequest;

typedef struct _rtcvish_emulator_v1_WriteResponse {
    char dummy_field;
} rtcvish_emulator_v1_WriteResponse;

typedef struct _rtcvish_emulator_v1_SaveStateRequest {
    char dummy_field;
} rtcvish_emulator_v1_SaveStateRequest;

typedef struct _rtcvish_emulator_v1_SaveStateResponse {
    pb_bytes_array_t *data;
} rtcvish_emulator_v1_SaveStateResponse;

typedef struct _rtcvish_emulator_v1_LoadStateRequest {
    pb_bytes_array_t *data;
} rtcvish_emulator_v1_LoadStateRequest;

typedef struct _rtcvish_emulator_v1_LoadStateResponse {
    char dummy_field;
} rtcvish_emulator_v1_LoadStateResponse;

/* Path on the emulator host. The response is sent after the ROM is
 loaded and emulation has started (or failed). */
typedef struct _rtcvish_emulator_v1_LoadRomRequest {
    char *path;
} rtcvish_emulator_v1_LoadRomRequest;

typedef struct _rtcvish_emulator_v1_LoadRomResponse {
    bool has_status;
    rtcvish_emulator_v1_Status status;
} rtcvish_emulator_v1_LoadRomResponse;

typedef struct _rtcvish_emulator_v1_CloseRomRequest {
    char dummy_field;
} rtcvish_emulator_v1_CloseRomRequest;

typedef struct _rtcvish_emulator_v1_CloseRomResponse {
    char dummy_field;
} rtcvish_emulator_v1_CloseRomResponse;

typedef struct _rtcvish_emulator_v1_ResetRequest {
    char dummy_field;
} rtcvish_emulator_v1_ResetRequest;

typedef struct _rtcvish_emulator_v1_ResetResponse {
    char dummy_field;
} rtcvish_emulator_v1_ResetResponse;

typedef struct _rtcvish_emulator_v1_PauseRequest {
    char dummy_field;
} rtcvish_emulator_v1_PauseRequest;

typedef struct _rtcvish_emulator_v1_PauseResponse {
    char dummy_field;
} rtcvish_emulator_v1_PauseResponse;

typedef struct _rtcvish_emulator_v1_ResumeRequest {
    char dummy_field;
} rtcvish_emulator_v1_ResumeRequest;

typedef struct _rtcvish_emulator_v1_ResumeResponse {
    char dummy_field;
} rtcvish_emulator_v1_ResumeResponse;

/* Emulate exactly `frames` frames and stay paused afterwards. If the
 emulator is running it pauses first. The response is sent after the
 last frame has been emulated. */
typedef struct _rtcvish_emulator_v1_StepRequest {
    uint32_t frames;
} rtcvish_emulator_v1_StepRequest;

typedef struct _rtcvish_emulator_v1_StepResponse {
    uint64_t frame;
} rtcvish_emulator_v1_StepResponse;

typedef struct _rtcvish_emulator_v1_StoreSource {
    char *domain;
    uint64_t address;
    /* false: sample once, on the first frame the unit executes.
 true: sample every frame the unit executes. */
    bool continuous;
} rtcvish_emulator_v1_StoreSource;

/* A unit is a memory write the emulator performs on its own at frame
 boundaries. Units are executed in the order they were applied, before
 each frame is emulated. */
typedef struct _rtcvish_emulator_v1_Unit {
    uint64_t id;
    char *domain;
    uint64_t address;
    uint32_t size;
    pb_size_t which_source;
    union {
        /* Bytes written as-is. */
        pb_bytes_array_t *value;
        /* Bytes read from another location. */
        rtcvish_emulator_v1_StoreSource store;
    } source;
    /* Added to the sampled value of a store unit before writing, with
 wrap-around integer arithmetic on the unit's size (1, 2, 4 or 8 bytes)
 and the domain's endianness. Ignored for value units. */
    int64_t tilt;
    /* Frames to wait after apply before the first execution. */
    uint32_t delay;
    /* Number of frames the unit executes. 0 means forever. */
    uint32_t lifetime;
    /* Re-schedule the unit after its lifetime ends. Ignored when lifetime is 0. */
    bool loop;
    /* Frames to wait after each loop before executing again, used as-is:
 0 executes again on the very next frame. delay applies only to the
 first execution. */
    uint32_t loop_delay;
    /* How the write is enforced while the unit executes (see Mode). */
    rtcvish_emulator_v1_Mode mode;
} rtcvish_emulator_v1_Unit;

typedef struct _rtcvish_emulator_v1_ApplyUnitsRequest {
    pb_size_t units_count;
    struct _rtcvish_emulator_v1_Unit *units;
} rtcvish_emulator_v1_ApplyUnitsRequest;

typedef struct _rtcvish_emulator_v1_ApplyUnitsResponse {
    char dummy_field;
} rtcvish_emulator_v1_ApplyUnitsResponse;

typedef struct _rtcvish_emulator_v1_RemoveUnitsRequest {
    pb_size_t ids_count;
    uint64_t *ids;
} rtcvish_emulator_v1_RemoveUnitsRequest;

typedef struct _rtcvish_emulator_v1_RemoveUnitsResponse {
    char dummy_field;
} rtcvish_emulator_v1_RemoveUnitsResponse;

typedef struct _rtcvish_emulator_v1_ClearUnitsRequest {
    char dummy_field;
} rtcvish_emulator_v1_ClearUnitsRequest;

typedef struct _rtcvish_emulator_v1_ClearUnitsResponse {
    char dummy_field;
} rtcvish_emulator_v1_ClearUnitsResponse;

typedef struct _rtcvish_emulator_v1_ListUnitsRequest {
    /* false (default): value units are listed with an empty value and their
 size set, so the response stays small however large the units are.
 Store units are listed unchanged. true: values are included, which
 can exceed the message size limit with many large units. */
    bool include_values;
} rtcvish_emulator_v1_ListUnitsRequest;

typedef struct _rtcvish_emulator_v1_ListUnitsResponse {
    /* Units that are queued or executing, in apply order. */
    pb_size_t units_count;
    struct _rtcvish_emulator_v1_Unit *units;
} rtcvish_emulator_v1_ListUnitsResponse;

/* Override controller input. Pressed buttons are OR-ed with the user's
 input until cleared. Button bit assignments are emulator-specific and
 documented per emulator. */
typedef struct _rtcvish_emulator_v1_SetInputRequest {
    uint32_t buttons;
    bool touch;
    uint32_t touch_x;
    uint32_t touch_y;
    bool clear;
} rtcvish_emulator_v1_SetInputRequest;

typedef struct _rtcvish_emulator_v1_SetInputResponse {
    char dummy_field;
} rtcvish_emulator_v1_SetInputResponse;

typedef struct _rtcvish_emulator_v1_Image {
    uint32_t width;
    uint32_t height;
    pb_bytes_array_t *rgba;
} rtcvish_emulator_v1_Image;

typedef struct _rtcvish_emulator_v1_ScreenshotRequest {
    char dummy_field;
} rtcvish_emulator_v1_ScreenshotRequest;

typedef struct _rtcvish_emulator_v1_ScreenshotResponse {
    pb_size_t screens_count;
    struct _rtcvish_emulator_v1_Image *screens;
} rtcvish_emulator_v1_ScreenshotResponse;

/* Ask for FrameEvent every `frame_interval` frames (0 disables). */
typedef struct _rtcvish_emulator_v1_SubscribeRequest {
    uint32_t frame_interval;
} rtcvish_emulator_v1_SubscribeRequest;

typedef struct _rtcvish_emulator_v1_SubscribeResponse {
    char dummy_field;
} rtcvish_emulator_v1_SubscribeResponse;

typedef struct _rtcvish_emulator_v1_PingRequest {
    char dummy_field;
} rtcvish_emulator_v1_PingRequest;

typedef struct _rtcvish_emulator_v1_PingResponse {
    char dummy_field;
} rtcvish_emulator_v1_PingResponse;

/* Close the emulator process. */
typedef struct _rtcvish_emulator_v1_QuitRequest {
    char dummy_field;
} rtcvish_emulator_v1_QuitRequest;

typedef struct _rtcvish_emulator_v1_Request {
    uint32_t id;
    pb_size_t which_body;
    union {
        rtcvish_emulator_v1_HelloRequest hello;
        rtcvish_emulator_v1_GetStatusRequest get_status;
        rtcvish_emulator_v1_ListDomainsRequest list_domains;
        rtcvish_emulator_v1_ReadRequest read;
        rtcvish_emulator_v1_WriteRequest write;
        rtcvish_emulator_v1_SaveStateRequest save_state;
        rtcvish_emulator_v1_LoadStateRequest load_state;
        rtcvish_emulator_v1_LoadRomRequest load_rom;
        rtcvish_emulator_v1_CloseRomRequest close_rom;
        rtcvish_emulator_v1_ResetRequest reset;
        rtcvish_emulator_v1_PauseRequest pause;
        rtcvish_emulator_v1_ResumeRequest resume;
        rtcvish_emulator_v1_StepRequest step;
        rtcvish_emulator_v1_ApplyUnitsRequest apply_units;
        rtcvish_emulator_v1_RemoveUnitsRequest remove_units;
        rtcvish_emulator_v1_ClearUnitsRequest clear_units;
        rtcvish_emulator_v1_ListUnitsRequest list_units;
        rtcvish_emulator_v1_SetInputRequest set_input;
        rtcvish_emulator_v1_ScreenshotRequest screenshot;
        rtcvish_emulator_v1_SubscribeRequest subscribe;
        rtcvish_emulator_v1_PingRequest ping;
        rtcvish_emulator_v1_QuitRequest quit;
    } body;
} rtcvish_emulator_v1_Request;

typedef struct _rtcvish_emulator_v1_QuitResponse {
    char dummy_field;
} rtcvish_emulator_v1_QuitResponse;

typedef struct _rtcvish_emulator_v1_Response {
    uint32_t id;
    pb_size_t which_body;
    union {
        rtcvish_emulator_v1_Error error;
        rtcvish_emulator_v1_HelloResponse hello;
        rtcvish_emulator_v1_GetStatusResponse get_status;
        rtcvish_emulator_v1_ListDomainsResponse list_domains;
        rtcvish_emulator_v1_ReadResponse read;
        rtcvish_emulator_v1_WriteResponse write;
        rtcvish_emulator_v1_SaveStateResponse save_state;
        rtcvish_emulator_v1_LoadStateResponse load_state;
        rtcvish_emulator_v1_LoadRomResponse load_rom;
        rtcvish_emulator_v1_CloseRomResponse close_rom;
        rtcvish_emulator_v1_ResetResponse reset;
        rtcvish_emulator_v1_PauseResponse pause;
        rtcvish_emulator_v1_ResumeResponse resume;
        rtcvish_emulator_v1_StepResponse step;
        rtcvish_emulator_v1_ApplyUnitsResponse apply_units;
        rtcvish_emulator_v1_RemoveUnitsResponse remove_units;
        rtcvish_emulator_v1_ClearUnitsResponse clear_units;
        rtcvish_emulator_v1_ListUnitsResponse list_units;
        rtcvish_emulator_v1_SetInputResponse set_input;
        rtcvish_emulator_v1_ScreenshotResponse screenshot;
        rtcvish_emulator_v1_SubscribeResponse subscribe;
        rtcvish_emulator_v1_PingResponse ping;
        rtcvish_emulator_v1_QuitResponse quit;
    } body;
} rtcvish_emulator_v1_Response;

typedef struct _rtcvish_emulator_v1_FrameEvent {
    uint64_t frame;
} rtcvish_emulator_v1_FrameEvent;

typedef struct _rtcvish_emulator_v1_StatusEvent {
    bool has_status;
    rtcvish_emulator_v1_Status status;
} rtcvish_emulator_v1_StatusEvent;

typedef struct _rtcvish_emulator_v1_Event {
    pb_size_t which_body;
    union {
        rtcvish_emulator_v1_FrameEvent frame;
        rtcvish_emulator_v1_StatusEvent status;
    } body;
} rtcvish_emulator_v1_Event;

typedef struct _rtcvish_emulator_v1_Message {
    pb_size_t which_body;
    union {
        rtcvish_emulator_v1_Request request;
        rtcvish_emulator_v1_Response response;
        rtcvish_emulator_v1_Event event;
    } body;
} rtcvish_emulator_v1_Message;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _rtcvish_emulator_v1_Mode_MIN rtcvish_emulator_v1_Mode_FRAME
#define _rtcvish_emulator_v1_Mode_MAX rtcvish_emulator_v1_Mode_HARD
#define _rtcvish_emulator_v1_Mode_ARRAYSIZE ((rtcvish_emulator_v1_Mode)(rtcvish_emulator_v1_Mode_HARD+1))

#define _rtcvish_emulator_v1_Error_Code_MIN rtcvish_emulator_v1_Error_Code_UNKNOWN
#define _rtcvish_emulator_v1_Error_Code_MAX rtcvish_emulator_v1_Error_Code_BUSY
#define _rtcvish_emulator_v1_Error_Code_ARRAYSIZE ((rtcvish_emulator_v1_Error_Code)(rtcvish_emulator_v1_Error_Code_BUSY+1))

#define _rtcvish_emulator_v1_Status_State_MIN rtcvish_emulator_v1_Status_State_NO_ROM
#define _rtcvish_emulator_v1_Status_State_MAX rtcvish_emulator_v1_Status_State_PAUSED
#define _rtcvish_emulator_v1_Status_State_ARRAYSIZE ((rtcvish_emulator_v1_Status_State)(rtcvish_emulator_v1_Status_State_PAUSED+1))





#define rtcvish_emulator_v1_Error_code_ENUMTYPE rtcvish_emulator_v1_Error_Code




#define rtcvish_emulator_v1_Status_state_ENUMTYPE rtcvish_emulator_v1_Status_State




























#define rtcvish_emulator_v1_Unit_mode_ENUMTYPE rtcvish_emulator_v1_Mode
























/* Initializer values for message structs */
#define rtcvish_emulator_v1_Message_init_default {0, {rtcvish_emulator_v1_Request_init_default}}
#define rtcvish_emulator_v1_Request_init_default {0, 0, {rtcvish_emulator_v1_HelloRequest_init_default}}
#define rtcvish_emulator_v1_Response_init_default {0, 0, {rtcvish_emulator_v1_Error_init_default}}
#define rtcvish_emulator_v1_Event_init_default   {0, {rtcvish_emulator_v1_FrameEvent_init_default}}
#define rtcvish_emulator_v1_Error_init_default   {_rtcvish_emulator_v1_Error_Code_MIN, NULL}
#define rtcvish_emulator_v1_HelloRequest_init_default {0, NULL}
#define rtcvish_emulator_v1_HelloResponse_init_default {0, NULL, NULL, NULL, false, rtcvish_emulator_v1_Capabilities_init_default}
#define rtcvish_emulator_v1_Capabilities_init_default {0, 0, 0, 0, 0, 0, 0, 0}
#define rtcvish_emulator_v1_Status_init_default  {_rtcvish_emulator_v1_Status_State_MIN, 0, NULL, NULL, NULL, NULL}
#define rtcvish_emulator_v1_GetStatusRequest_init_default {0}
#define rtcvish_emulator_v1_GetStatusResponse_init_default {false, rtcvish_emulator_v1_Status_init_default}
#define rtcvish_emulator_v1_Domain_init_default  {NULL, 0, 0, 0, 0, 0}
#define rtcvish_emulator_v1_ListDomainsRequest_init_default {0}
#define rtcvish_emulator_v1_ListDomainsResponse_init_default {0, NULL}
#define rtcvish_emulator_v1_Range_init_default   {NULL, 0, 0}
#define rtcvish_emulator_v1_ReadRequest_init_default {0, NULL}
#define rtcvish_emulator_v1_ReadResponse_init_default {0, NULL}
#define rtcvish_emulator_v1_WriteChunk_init_default {NULL, 0, NULL}
#define rtcvish_emulator_v1_WriteRequest_init_default {0, NULL}
#define rtcvish_emulator_v1_WriteResponse_init_default {0}
#define rtcvish_emulator_v1_SaveStateRequest_init_default {0}
#define rtcvish_emulator_v1_SaveStateResponse_init_default {NULL}
#define rtcvish_emulator_v1_LoadStateRequest_init_default {NULL}
#define rtcvish_emulator_v1_LoadStateResponse_init_default {0}
#define rtcvish_emulator_v1_LoadRomRequest_init_default {NULL}
#define rtcvish_emulator_v1_LoadRomResponse_init_default {false, rtcvish_emulator_v1_Status_init_default}
#define rtcvish_emulator_v1_CloseRomRequest_init_default {0}
#define rtcvish_emulator_v1_CloseRomResponse_init_default {0}
#define rtcvish_emulator_v1_ResetRequest_init_default {0}
#define rtcvish_emulator_v1_ResetResponse_init_default {0}
#define rtcvish_emulator_v1_PauseRequest_init_default {0}
#define rtcvish_emulator_v1_PauseResponse_init_default {0}
#define rtcvish_emulator_v1_ResumeRequest_init_default {0}
#define rtcvish_emulator_v1_ResumeResponse_init_default {0}
#define rtcvish_emulator_v1_StepRequest_init_default {0}
#define rtcvish_emulator_v1_StepResponse_init_default {0}
#define rtcvish_emulator_v1_Unit_init_default    {0, NULL, 0, 0, 0, {NULL}, 0, 0, 0, 0, 0, _rtcvish_emulator_v1_Mode_MIN}
#define rtcvish_emulator_v1_StoreSource_init_default {NULL, 0, 0}
#define rtcvish_emulator_v1_ApplyUnitsRequest_init_default {0, NULL}
#define rtcvish_emulator_v1_ApplyUnitsResponse_init_default {0}
#define rtcvish_emulator_v1_RemoveUnitsRequest_init_default {0, NULL}
#define rtcvish_emulator_v1_RemoveUnitsResponse_init_default {0}
#define rtcvish_emulator_v1_ClearUnitsRequest_init_default {0}
#define rtcvish_emulator_v1_ClearUnitsResponse_init_default {0}
#define rtcvish_emulator_v1_ListUnitsRequest_init_default {0}
#define rtcvish_emulator_v1_ListUnitsResponse_init_default {0, NULL}
#define rtcvish_emulator_v1_SetInputRequest_init_default {0, 0, 0, 0, 0}
#define rtcvish_emulator_v1_SetInputResponse_init_default {0}
#define rtcvish_emulator_v1_Image_init_default   {0, 0, NULL}
#define rtcvish_emulator_v1_ScreenshotRequest_init_default {0}
#define rtcvish_emulator_v1_ScreenshotResponse_init_default {0, NULL}
#define rtcvish_emulator_v1_SubscribeRequest_init_default {0}
#define rtcvish_emulator_v1_SubscribeResponse_init_default {0}
#define rtcvish_emulator_v1_PingRequest_init_default {0}
#define rtcvish_emulator_v1_PingResponse_init_default {0}
#define rtcvish_emulator_v1_QuitRequest_init_default {0}
#define rtcvish_emulator_v1_QuitResponse_init_default {0}
#define rtcvish_emulator_v1_FrameEvent_init_default {0}
#define rtcvish_emulator_v1_StatusEvent_init_default {false, rtcvish_emulator_v1_Status_init_default}
#define rtcvish_emulator_v1_Message_init_zero    {0, {rtcvish_emulator_v1_Request_init_zero}}
#define rtcvish_emulator_v1_Request_init_zero    {0, 0, {rtcvish_emulator_v1_HelloRequest_init_zero}}
#define rtcvish_emulator_v1_Response_init_zero   {0, 0, {rtcvish_emulator_v1_Error_init_zero}}
#define rtcvish_emulator_v1_Event_init_zero      {0, {rtcvish_emulator_v1_FrameEvent_init_zero}}
#define rtcvish_emulator_v1_Error_init_zero      {_rtcvish_emulator_v1_Error_Code_MIN, NULL}
#define rtcvish_emulator_v1_HelloRequest_init_zero {0, NULL}
#define rtcvish_emulator_v1_HelloResponse_init_zero {0, NULL, NULL, NULL, false, rtcvish_emulator_v1_Capabilities_init_zero}
#define rtcvish_emulator_v1_Capabilities_init_zero {0, 0, 0, 0, 0, 0, 0, 0}
#define rtcvish_emulator_v1_Status_init_zero     {_rtcvish_emulator_v1_Status_State_MIN, 0, NULL, NULL, NULL, NULL}
#define rtcvish_emulator_v1_GetStatusRequest_init_zero {0}
#define rtcvish_emulator_v1_GetStatusResponse_init_zero {false, rtcvish_emulator_v1_Status_init_zero}
#define rtcvish_emulator_v1_Domain_init_zero     {NULL, 0, 0, 0, 0, 0}
#define rtcvish_emulator_v1_ListDomainsRequest_init_zero {0}
#define rtcvish_emulator_v1_ListDomainsResponse_init_zero {0, NULL}
#define rtcvish_emulator_v1_Range_init_zero      {NULL, 0, 0}
#define rtcvish_emulator_v1_ReadRequest_init_zero {0, NULL}
#define rtcvish_emulator_v1_ReadResponse_init_zero {0, NULL}
#define rtcvish_emulator_v1_WriteChunk_init_zero {NULL, 0, NULL}
#define rtcvish_emulator_v1_WriteRequest_init_zero {0, NULL}
#define rtcvish_emulator_v1_WriteResponse_init_zero {0}
#define rtcvish_emulator_v1_SaveStateRequest_init_zero {0}
#define rtcvish_emulator_v1_SaveStateResponse_init_zero {NULL}
#define rtcvish_emulator_v1_LoadStateRequest_init_zero {NULL}
#define rtcvish_emulator_v1_LoadStateResponse_init_zero {0}
#define rtcvish_emulator_v1_LoadRomRequest_init_zero {NULL}
#define rtcvish_emulator_v1_LoadRomResponse_init_zero {false, rtcvish_emulator_v1_Status_init_zero}
#define rtcvish_emulator_v1_CloseRomRequest_init_zero {0}
#define rtcvish_emulator_v1_CloseRomResponse_init_zero {0}
#define rtcvish_emulator_v1_ResetRequest_init_zero {0}
#define rtcvish_emulator_v1_ResetResponse_init_zero {0}
#define rtcvish_emulator_v1_PauseRequest_init_zero {0}
#define rtcvish_emulator_v1_PauseResponse_init_zero {0}
#define rtcvish_emulator_v1_ResumeRequest_init_zero {0}
#define rtcvish_emulator_v1_ResumeResponse_init_zero {0}
#define rtcvish_emulator_v1_StepRequest_init_zero {0}
#define rtcvish_emulator_v1_StepResponse_init_zero {0}
#define rtcvish_emulator_v1_Unit_init_zero       {0, NULL, 0, 0, 0, {NULL}, 0, 0, 0, 0, 0, _rtcvish_emulator_v1_Mode_MIN}
#define rtcvish_emulator_v1_StoreSource_init_zero {NULL, 0, 0}
#define rtcvish_emulator_v1_ApplyUnitsRequest_init_zero {0, NULL}
#define rtcvish_emulator_v1_ApplyUnitsResponse_init_zero {0}
#define rtcvish_emulator_v1_RemoveUnitsRequest_init_zero {0, NULL}
#define rtcvish_emulator_v1_RemoveUnitsResponse_init_zero {0}
#define rtcvish_emulator_v1_ClearUnitsRequest_init_zero {0}
#define rtcvish_emulator_v1_ClearUnitsResponse_init_zero {0}
#define rtcvish_emulator_v1_ListUnitsRequest_init_zero {0}
#define rtcvish_emulator_v1_ListUnitsResponse_init_zero {0, NULL}
#define rtcvish_emulator_v1_SetInputRequest_init_zero {0, 0, 0, 0, 0}
#define rtcvish_emulator_v1_SetInputResponse_init_zero {0}
#define rtcvish_emulator_v1_Image_init_zero      {0, 0, NULL}
#define rtcvish_emulator_v1_ScreenshotRequest_init_zero {0}
#define rtcvish_emulator_v1_ScreenshotResponse_init_zero {0, NULL}
#define rtcvish_emulator_v1_SubscribeRequest_init_zero {0}
#define rtcvish_emulator_v1_SubscribeResponse_init_zero {0}
#define rtcvish_emulator_v1_PingRequest_init_zero {0}
#define rtcvish_emulator_v1_PingResponse_init_zero {0}
#define rtcvish_emulator_v1_QuitRequest_init_zero {0}
#define rtcvish_emulator_v1_QuitResponse_init_zero {0}
#define rtcvish_emulator_v1_FrameEvent_init_zero {0}
#define rtcvish_emulator_v1_StatusEvent_init_zero {false, rtcvish_emulator_v1_Status_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define rtcvish_emulator_v1_Error_code_tag       1
#define rtcvish_emulator_v1_Error_message_tag    2
#define rtcvish_emulator_v1_HelloRequest_protocol_version_tag 1
#define rtcvish_emulator_v1_HelloRequest_client_name_tag 2
#define rtcvish_emulator_v1_Capabilities_savestates_tag 1
#define rtcvish_emulator_v1_Capabilities_screenshot_tag 2
#define rtcvish_emulator_v1_Capabilities_input_tag 3
#define rtcvish_emulator_v1_Capabilities_load_rom_tag 4
#define rtcvish_emulator_v1_Capabilities_reset_tag 5
#define rtcvish_emulator_v1_Capabilities_max_payload_tag 6
#define rtcvish_emulator_v1_Capabilities_scanline_units_tag 7
#define rtcvish_emulator_v1_Capabilities_hard_units_tag 8
#define rtcvish_emulator_v1_HelloResponse_protocol_version_tag 1
#define rtcvish_emulator_v1_HelloResponse_emulator_tag 2
#define rtcvish_emulator_v1_HelloResponse_version_tag 3
#define rtcvish_emulator_v1_HelloResponse_system_tag 4
#define rtcvish_emulator_v1_HelloResponse_capabilities_tag 5
#define rtcvish_emulator_v1_Status_state_tag     1
#define rtcvish_emulator_v1_Status_frame_tag     2
#define rtcvish_emulator_v1_Status_rom_path_tag  3
#define rtcvish_emulator_v1_Status_game_title_tag 4
#define rtcvish_emulator_v1_Status_game_code_tag 5
#define rtcvish_emulator_v1_Status_console_tag   6
#define rtcvish_emulator_v1_GetStatusResponse_status_tag 1
#define rtcvish_emulator_v1_Domain_name_tag      1
#define rtcvish_emulator_v1_Domain_size_tag      2
#define rtcvish_emulator_v1_Domain_word_size_tag 3
#define rtcvish_emulator_v1_Domain_big_endian_tag 4
#define rtcvish_emulator_v1_Domain_writable_tag  5
#define rtcvish_emulator_v1_Domain_hidden_tag    6
#define rtcvish_emulator_v1_ListDomainsResponse_domains_tag 1
#define rtcvish_emulator_v1_Range_domain_tag     1
#define rtcvish_emulator_v1_Range_address_tag    2
#define rtcvish_emulator_v1_Range_size_tag       3
#define rtcvish_emulator_v1_ReadRequest_ranges_tag 1
#define rtcvish_emulator_v1_ReadResponse_data_tag 1
#define rtcvish_emulator_v1_WriteChunk_domain_tag 1
#define rtcvish_emulator_v1_WriteChunk_address_tag 2
#define rtcvish_emulator_v1_WriteChunk_data_tag  3
#define rtcvish_emulator_v1_WriteRequest_chunks_tag 1
#define rtcvish_emulator_v1_SaveStateResponse_data_tag 1
#define rtcvish_emulator_v1_LoadStateRequest_data_tag 1
#define rtcvish_emulator_v1_LoadRomRequest_path_tag 1
#define rtcvish_emulator_v1_LoadRomResponse_status_tag 1
#define rtcvish_emulator_v1_StepRequest_frames_tag 1
#define rtcvish_emulator_v1_StepResponse_frame_tag 1
#define rtcvish_emulator_v1_StoreSource_domain_tag 1
#define rtcvish_emulator_v1_StoreSource_address_tag 2
#define rtcvish_emulator_v1_StoreSource_continuous_tag 3
#define rtcvish_emulator_v1_Unit_id_tag          1
#define rtcvish_emulator_v1_Unit_domain_tag      2
#define rtcvish_emulator_v1_Unit_address_tag     3
#define rtcvish_emulator_v1_Unit_size_tag        4
#define rtcvish_emulator_v1_Unit_value_tag       5
#define rtcvish_emulator_v1_Unit_store_tag       6
#define rtcvish_emulator_v1_Unit_tilt_tag        7
#define rtcvish_emulator_v1_Unit_delay_tag       8
#define rtcvish_emulator_v1_Unit_lifetime_tag    9
#define rtcvish_emulator_v1_Unit_loop_tag        10
#define rtcvish_emulator_v1_Unit_loop_delay_tag  11
#define rtcvish_emulator_v1_Unit_mode_tag        12
#define rtcvish_emulator_v1_ApplyUnitsRequest_units_tag 1
#define rtcvish_emulator_v1_RemoveUnitsRequest_ids_tag 1
#define rtcvish_emulator_v1_ListUnitsRequest_include_values_tag 1
#define rtcvish_emulator_v1_ListUnitsResponse_units_tag 1
#define rtcvish_emulator_v1_SetInputRequest_buttons_tag 1
#define rtcvish_emulator_v1_SetInputRequest_touch_tag 2
#define rtcvish_emulator_v1_SetInputRequest_touch_x_tag 3
#define rtcvish_emulator_v1_SetInputRequest_touch_y_tag 4
#define rtcvish_emulator_v1_SetInputRequest_clear_tag 5
#define rtcvish_emulator_v1_Image_width_tag      1
#define rtcvish_emulator_v1_Image_height_tag     2
#define rtcvish_emulator_v1_Image_rgba_tag       3
#define rtcvish_emulator_v1_ScreenshotResponse_screens_tag 1
#define rtcvish_emulator_v1_SubscribeRequest_frame_interval_tag 1
#define rtcvish_emulator_v1_Request_id_tag       1
#define rtcvish_emulator_v1_Request_hello_tag    10
#define rtcvish_emulator_v1_Request_get_status_tag 11
#define rtcvish_emulator_v1_Request_list_domains_tag 12
#define rtcvish_emulator_v1_Request_read_tag     13
#define rtcvish_emulator_v1_Request_write_tag    14
#define rtcvish_emulator_v1_Request_save_state_tag 15
#define rtcvish_emulator_v1_Request_load_state_tag 16
#define rtcvish_emulator_v1_Request_load_rom_tag 17
#define rtcvish_emulator_v1_Request_close_rom_tag 18
#define rtcvish_emulator_v1_Request_reset_tag    19
#define rtcvish_emulator_v1_Request_pause_tag    20
#define rtcvish_emulator_v1_Request_resume_tag   21
#define rtcvish_emulator_v1_Request_step_tag     22
#define rtcvish_emulator_v1_Request_apply_units_tag 23
#define rtcvish_emulator_v1_Request_remove_units_tag 24
#define rtcvish_emulator_v1_Request_clear_units_tag 25
#define rtcvish_emulator_v1_Request_list_units_tag 26
#define rtcvish_emulator_v1_Request_set_input_tag 27
#define rtcvish_emulator_v1_Request_screenshot_tag 28
#define rtcvish_emulator_v1_Request_subscribe_tag 29
#define rtcvish_emulator_v1_Request_ping_tag     30
#define rtcvish_emulator_v1_Request_quit_tag     31
#define rtcvish_emulator_v1_Response_id_tag      1
#define rtcvish_emulator_v1_Response_error_tag   2
#define rtcvish_emulator_v1_Response_hello_tag   10
#define rtcvish_emulator_v1_Response_get_status_tag 11
#define rtcvish_emulator_v1_Response_list_domains_tag 12
#define rtcvish_emulator_v1_Response_read_tag    13
#define rtcvish_emulator_v1_Response_write_tag   14
#define rtcvish_emulator_v1_Response_save_state_tag 15
#define rtcvish_emulator_v1_Response_load_state_tag 16
#define rtcvish_emulator_v1_Response_load_rom_tag 17
#define rtcvish_emulator_v1_Response_close_rom_tag 18
#define rtcvish_emulator_v1_Response_reset_tag   19
#define rtcvish_emulator_v1_Response_pause_tag   20
#define rtcvish_emulator_v1_Response_resume_tag  21
#define rtcvish_emulator_v1_Response_step_tag    22
#define rtcvish_emulator_v1_Response_apply_units_tag 23
#define rtcvish_emulator_v1_Response_remove_units_tag 24
#define rtcvish_emulator_v1_Response_clear_units_tag 25
#define rtcvish_emulator_v1_Response_list_units_tag 26
#define rtcvish_emulator_v1_Response_set_input_tag 27
#define rtcvish_emulator_v1_Response_screenshot_tag 28
#define rtcvish_emulator_v1_Response_subscribe_tag 29
#define rtcvish_emulator_v1_Response_ping_tag    30
#define rtcvish_emulator_v1_Response_quit_tag    31
#define rtcvish_emulator_v1_FrameEvent_frame_tag 1
#define rtcvish_emulator_v1_StatusEvent_status_tag 1
#define rtcvish_emulator_v1_Event_frame_tag      1
#define rtcvish_emulator_v1_Event_status_tag     2
#define rtcvish_emulator_v1_Message_request_tag  1
#define rtcvish_emulator_v1_Message_response_tag 2
#define rtcvish_emulator_v1_Message_event_tag    3

/* Struct field encoding specification for nanopb */
#define rtcvish_emulator_v1_Message_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,request,body.request),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,response,body.response),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,event,body.event),   3)
#define rtcvish_emulator_v1_Message_CALLBACK NULL
#define rtcvish_emulator_v1_Message_DEFAULT NULL
#define rtcvish_emulator_v1_Message_body_request_MSGTYPE rtcvish_emulator_v1_Request
#define rtcvish_emulator_v1_Message_body_response_MSGTYPE rtcvish_emulator_v1_Response
#define rtcvish_emulator_v1_Message_body_event_MSGTYPE rtcvish_emulator_v1_Event

#define rtcvish_emulator_v1_Request_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,hello,body.hello),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,get_status,body.get_status),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,list_domains,body.list_domains),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,read,body.read),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,write,body.write),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,save_state,body.save_state),  15) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,load_state,body.load_state),  16) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,load_rom,body.load_rom),  17) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,close_rom,body.close_rom),  18) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,reset,body.reset),  19) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,pause,body.pause),  20) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,resume,body.resume),  21) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,step,body.step),  22) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,apply_units,body.apply_units),  23) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,remove_units,body.remove_units),  24) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,clear_units,body.clear_units),  25) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,list_units,body.list_units),  26) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,set_input,body.set_input),  27) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,screenshot,body.screenshot),  28) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,subscribe,body.subscribe),  29) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,ping,body.ping),  30) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,quit,body.quit),  31)
#define rtcvish_emulator_v1_Request_CALLBACK NULL
#define rtcvish_emulator_v1_Request_DEFAULT NULL
#define rtcvish_emulator_v1_Request_body_hello_MSGTYPE rtcvish_emulator_v1_HelloRequest
#define rtcvish_emulator_v1_Request_body_get_status_MSGTYPE rtcvish_emulator_v1_GetStatusRequest
#define rtcvish_emulator_v1_Request_body_list_domains_MSGTYPE rtcvish_emulator_v1_ListDomainsRequest
#define rtcvish_emulator_v1_Request_body_read_MSGTYPE rtcvish_emulator_v1_ReadRequest
#define rtcvish_emulator_v1_Request_body_write_MSGTYPE rtcvish_emulator_v1_WriteRequest
#define rtcvish_emulator_v1_Request_body_save_state_MSGTYPE rtcvish_emulator_v1_SaveStateRequest
#define rtcvish_emulator_v1_Request_body_load_state_MSGTYPE rtcvish_emulator_v1_LoadStateRequest
#define rtcvish_emulator_v1_Request_body_load_rom_MSGTYPE rtcvish_emulator_v1_LoadRomRequest
#define rtcvish_emulator_v1_Request_body_close_rom_MSGTYPE rtcvish_emulator_v1_CloseRomRequest
#define rtcvish_emulator_v1_Request_body_reset_MSGTYPE rtcvish_emulator_v1_ResetRequest
#define rtcvish_emulator_v1_Request_body_pause_MSGTYPE rtcvish_emulator_v1_PauseRequest
#define rtcvish_emulator_v1_Request_body_resume_MSGTYPE rtcvish_emulator_v1_ResumeRequest
#define rtcvish_emulator_v1_Request_body_step_MSGTYPE rtcvish_emulator_v1_StepRequest
#define rtcvish_emulator_v1_Request_body_apply_units_MSGTYPE rtcvish_emulator_v1_ApplyUnitsRequest
#define rtcvish_emulator_v1_Request_body_remove_units_MSGTYPE rtcvish_emulator_v1_RemoveUnitsRequest
#define rtcvish_emulator_v1_Request_body_clear_units_MSGTYPE rtcvish_emulator_v1_ClearUnitsRequest
#define rtcvish_emulator_v1_Request_body_list_units_MSGTYPE rtcvish_emulator_v1_ListUnitsRequest
#define rtcvish_emulator_v1_Request_body_set_input_MSGTYPE rtcvish_emulator_v1_SetInputRequest
#define rtcvish_emulator_v1_Request_body_screenshot_MSGTYPE rtcvish_emulator_v1_ScreenshotRequest
#define rtcvish_emulator_v1_Request_body_subscribe_MSGTYPE rtcvish_emulator_v1_SubscribeRequest
#define rtcvish_emulator_v1_Request_body_ping_MSGTYPE rtcvish_emulator_v1_PingRequest
#define rtcvish_emulator_v1_Request_body_quit_MSGTYPE rtcvish_emulator_v1_QuitRequest

#define rtcvish_emulator_v1_Response_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,error,body.error),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,hello,body.hello),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,get_status,body.get_status),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,list_domains,body.list_domains),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,read,body.read),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,write,body.write),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,save_state,body.save_state),  15) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,load_state,body.load_state),  16) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,load_rom,body.load_rom),  17) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,close_rom,body.close_rom),  18) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,reset,body.reset),  19) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,pause,body.pause),  20) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,resume,body.resume),  21) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,step,body.step),  22) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,apply_units,body.apply_units),  23) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,remove_units,body.remove_units),  24) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,clear_units,body.clear_units),  25) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,list_units,body.list_units),  26) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,set_input,body.set_input),  27) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,screenshot,body.screenshot),  28) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,subscribe,body.subscribe),  29) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,ping,body.ping),  30) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,quit,body.quit),  31)
#define rtcvish_emulator_v1_Response_CALLBACK NULL
#define rtcvish_emulator_v1_Response_DEFAULT NULL
#define rtcvish_emulator_v1_Response_body_error_MSGTYPE rtcvish_emulator_v1_Error
#define rtcvish_emulator_v1_Response_body_hello_MSGTYPE rtcvish_emulator_v1_HelloResponse
#define rtcvish_emulator_v1_Response_body_get_status_MSGTYPE rtcvish_emulator_v1_GetStatusResponse
#define rtcvish_emulator_v1_Response_body_list_domains_MSGTYPE rtcvish_emulator_v1_ListDomainsResponse
#define rtcvish_emulator_v1_Response_body_read_MSGTYPE rtcvish_emulator_v1_ReadResponse
#define rtcvish_emulator_v1_Response_body_write_MSGTYPE rtcvish_emulator_v1_WriteResponse
#define rtcvish_emulator_v1_Response_body_save_state_MSGTYPE rtcvish_emulator_v1_SaveStateResponse
#define rtcvish_emulator_v1_Response_body_load_state_MSGTYPE rtcvish_emulator_v1_LoadStateResponse
#define rtcvish_emulator_v1_Response_body_load_rom_MSGTYPE rtcvish_emulator_v1_LoadRomResponse
#define rtcvish_emulator_v1_Response_body_close_rom_MSGTYPE rtcvish_emulator_v1_CloseRomResponse
#define rtcvish_emulator_v1_Response_body_reset_MSGTYPE rtcvish_emulator_v1_ResetResponse
#define rtcvish_emulator_v1_Response_body_pause_MSGTYPE rtcvish_emulator_v1_PauseResponse
#define rtcvish_emulator_v1_Response_body_resume_MSGTYPE rtcvish_emulator_v1_ResumeResponse
#define rtcvish_emulator_v1_Response_body_step_MSGTYPE rtcvish_emulator_v1_StepResponse
#define rtcvish_emulator_v1_Response_body_apply_units_MSGTYPE rtcvish_emulator_v1_ApplyUnitsResponse
#define rtcvish_emulator_v1_Response_body_remove_units_MSGTYPE rtcvish_emulator_v1_RemoveUnitsResponse
#define rtcvish_emulator_v1_Response_body_clear_units_MSGTYPE rtcvish_emulator_v1_ClearUnitsResponse
#define rtcvish_emulator_v1_Response_body_list_units_MSGTYPE rtcvish_emulator_v1_ListUnitsResponse
#define rtcvish_emulator_v1_Response_body_set_input_MSGTYPE rtcvish_emulator_v1_SetInputResponse
#define rtcvish_emulator_v1_Response_body_screenshot_MSGTYPE rtcvish_emulator_v1_ScreenshotResponse
#define rtcvish_emulator_v1_Response_body_subscribe_MSGTYPE rtcvish_emulator_v1_SubscribeResponse
#define rtcvish_emulator_v1_Response_body_ping_MSGTYPE rtcvish_emulator_v1_PingResponse
#define rtcvish_emulator_v1_Response_body_quit_MSGTYPE rtcvish_emulator_v1_QuitResponse

#define rtcvish_emulator_v1_Event_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,frame,body.frame),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,status,body.status),   2)
#define rtcvish_emulator_v1_Event_CALLBACK NULL
#define rtcvish_emulator_v1_Event_DEFAULT NULL
#define rtcvish_emulator_v1_Event_body_frame_MSGTYPE rtcvish_emulator_v1_FrameEvent
#define rtcvish_emulator_v1_Event_body_status_MSGTYPE rtcvish_emulator_v1_StatusEvent

#define rtcvish_emulator_v1_Error_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    code,              1) \
X(a, POINTER,  SINGULAR, STRING,   message,           2)
#define rtcvish_emulator_v1_Error_CALLBACK NULL
#define rtcvish_emulator_v1_Error_DEFAULT NULL

#define rtcvish_emulator_v1_HelloRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   protocol_version,   1) \
X(a, POINTER,  SINGULAR, STRING,   client_name,       2)
#define rtcvish_emulator_v1_HelloRequest_CALLBACK NULL
#define rtcvish_emulator_v1_HelloRequest_DEFAULT NULL

#define rtcvish_emulator_v1_HelloResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   protocol_version,   1) \
X(a, POINTER,  SINGULAR, STRING,   emulator,          2) \
X(a, POINTER,  SINGULAR, STRING,   version,           3) \
X(a, POINTER,  SINGULAR, STRING,   system,            4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  capabilities,      5)
#define rtcvish_emulator_v1_HelloResponse_CALLBACK NULL
#define rtcvish_emulator_v1_HelloResponse_DEFAULT NULL
#define rtcvish_emulator_v1_HelloResponse_capabilities_MSGTYPE rtcvish_emulator_v1_Capabilities

#define rtcvish_emulator_v1_Capabilities_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     savestates,        1) \
X(a, STATIC,   SINGULAR, BOOL,     screenshot,        2) \
X(a, STATIC,   SINGULAR, BOOL,     input,             3) \
X(a, STATIC,   SINGULAR, BOOL,     load_rom,          4) \
X(a, STATIC,   SINGULAR, BOOL,     reset,             5) \
X(a, STATIC,   SINGULAR, UINT32,   max_payload,       6) \
X(a, STATIC,   SINGULAR, BOOL,     scanline_units,    7) \
X(a, STATIC,   SINGULAR, BOOL,     hard_units,        8)
#define rtcvish_emulator_v1_Capabilities_CALLBACK NULL
#define rtcvish_emulator_v1_Capabilities_DEFAULT NULL

#define rtcvish_emulator_v1_Status_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    state,             1) \
X(a, STATIC,   SINGULAR, UINT64,   frame,             2) \
X(a, POINTER,  SINGULAR, STRING,   rom_path,          3) \
X(a, POINTER,  SINGULAR, STRING,   game_title,        4) \
X(a, POINTER,  SINGULAR, STRING,   game_code,         5) \
X(a, POINTER,  SINGULAR, STRING,   console,           6)
#define rtcvish_emulator_v1_Status_CALLBACK NULL
#define rtcvish_emulator_v1_Status_DEFAULT NULL

#define rtcvish_emulator_v1_GetStatusRequest_FIELDLIST(X, a) \

#define rtcvish_emulator_v1_GetStatusRequest_CALLBACK NULL
#define rtcvish_emulator_v1_GetStatusRequest_DEFAULT NULL

#define rtcvish_emulator_v1_GetStatusResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  status,            1)
#define rtcvish_emulator_v1_GetStatusResponse_CALLBACK NULL
#define rtcvish_emulator_v1_GetStatusResponse_DEFAULT NULL
#define rtcvish_emulator_v1_GetStatusResponse_status_MSGTYPE rtcvish_emulator_v1_Status

#define rtcvish_emulator_v1_Domain_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, UINT64,   size,              2) \
X(a, STATIC,   SINGULAR, UINT32,   word_size,         3) \
X(a, STATIC,   SINGULAR, BOOL,     big_endian,        4) \
X(a, STATIC,   SINGULAR, BOOL,     writable,          5) \
X(a, STATIC,   SINGULAR, BOOL,     hidden,            6)
#define rtcvish_emulator_v1_Domain_CALLBACK NULL
#define rtcvish_emulator_v1_Domain_DEFAULT NULL

#define rtcvish_emulator_v1_ListDomainsRequest_FIELDLIST(X, a) \

#define rtcvish_emulator_v1_ListDomainsRequest_CALLBACK NULL
#define rtcvish_emulator_v1_ListDomainsRequest_DEFAULT NULL

#define rtcvish_emulator_v1_ListDomainsResponse_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  domains,           1)
#define rtcvish_emulator_v1_ListDomainsResponse_CALLBACK NULL
#define rtcvish_emulator_v1_ListDomainsResponse_DEFAULT NULL
#define rtcvish_emulator_v1_ListDomainsResponse_domains_MSGTYPE rtcvish_emulator_v1_Domain

#define rtcvish_emulator_v1_Range_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   domain,            1) \
X(a, STATIC,   SINGULAR, UINT64,   address,           2) \
X(a, STATIC,   SINGULAR, UINT32,   size,              3)
#define rtcvish_emulator_v1_Range_CALLBACK NULL
#define rtcvish_emulator_v1_Range_DEFAULT NULL

#define rtcvish_emulator_v1_ReadRequest_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  ranges,            1)
#define rtcvish_emulator_v1_ReadRequest_CALLBACK NULL
#define rtcvish_emulator_v1_ReadRequest_DEFAULT NULL
#define rtcvish_emulator_v1_ReadRequest_ranges_MSGTYPE rtcvish_emulator_v1_Range

#define rtcvish_emulator_v1_ReadResponse_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, BYTES,    data,              1)
#define rtcvish_emulator_v1_ReadResponse_CALLBACK NULL
#define rtcvish_emulator_v1_ReadResponse_DEFAULT NULL

#define rtcvish_emulator_v1_WriteChunk_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   domain,            1) \
X(a, STATIC,   SINGULAR, UINT64,   address,           2) \
X(a, POINTER,  SINGULAR, BYTES,    data,              3)
#define rtcvish_emulator_v1_WriteChunk_CALLBACK NULL
#define rtcvish_emulator_v1_WriteChunk_DEFAULT NULL

#define rtcvish_emulator_v1_WriteRequest_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  chunks,            1)
#define rtcvish_emulator_v1_WriteRequest_CALLBACK NULL
#define rtcvish_emulator_v1_WriteRequest_DEFAULT NULL
#define rtcvish_emulator_v1_WriteRequest_chunks_MSGTYPE rtcvish_emulator_v1_WriteChunk

#define rtcvish_emulator_v1_WriteResponse_FIELDLIST(X, a) \

#define rtcvish_emulator_v1_WriteResponse_CALLBACK NULL
#define rtcvish_emulator_v1_WriteResponse_DEFAULT NULL

#define rtcvish_emulator_v1_SaveStateRequest_FIELDLIST(X, a) \

#define rtcvish_emulator_v1_SaveStateRequest_CALLBACK NULL
#define rtcvish_emulator_v1_SaveStateRequest_DEFAULT NULL

#define rtcvish_emulator_v1_SaveStateResponse_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, BYTES,    data,              1)
#define rtcvish_emulator_v1_SaveStateResponse_CALLBACK NULL
#define rtcvish_emulator_v1_SaveStateResponse_DEFAULT NULL

#define rtcvish_emulator_v1_LoadStateRequest_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, BYTES,    data,              1)
#define rtcvish_emulator_v1_LoadStateRequest_CALLBACK NULL
#define rtcvish_emulator_v1_LoadStateRequest_DEFAULT NULL

#define rtcvish_emulator_v1_LoadStateResponse_FIELDLIST(X, a) \

#define rtcvish_emulator_v1_LoadStateResponse_CALLBACK NULL
#define rtcvish_emulator_v1_LoadStateResponse_DEFAULT NULL

#define rtcvish_emulator_v1_LoadRomRequest_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   path,              1)
#define rtcvish_emulator_v1_LoadRomRequest_CALLBACK NULL
#define rtcvish_emulator_v1_LoadRomRequest_DEFAULT NULL

#define rtcvish_emulator_v1_LoadRomResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  status,            1)
#define rtcvish_emulator_v1_LoadRomResponse_CALLBACK NULL
#define rtcvish_emulator_v1_LoadRomResponse_DEFAULT NULL
#define rtcvish_emulator_v1_LoadRomResponse_status_MSGTYPE rtcvish_emulator_v1_Status

#define rtcvish_emulator_v1_CloseRomRequest_FIELDLIST(X, a) \

#define rtcvish_emulator_v1_CloseRomRequest_CALLBACK NULL
#define rtcvish_emulator_v1_CloseRomRequest_DEFAULT NULL

#define rtcvish_emulator_v1_CloseRomResponse_FIELDLIST(X, a) \

#define rtcvish_emulator_v1_CloseRomResponse_CALLBACK NULL
#define rtcvish_emulator_v1_CloseRomResponse_DEFAULT NULL

#define rtcvish_emulator_v1_ResetRequest_FIELDLIST(X, a) \

#define rtcvish_emulator_v1_ResetRequest_CALLBACK NULL
#define rtcvish_emulator_v1_ResetRequest_DEFAULT NULL

#define rtcvish_emulator_v1_ResetResponse_FIELDLIST(X, a) \

#define rtcvish_emulator_v1_ResetResponse_CALLBACK NULL
#define rtcvish_emulator_v1_ResetResponse_DEFAULT NULL

#define rtcvish_emulator_v1_PauseRequest_FIELDLIST(X, a) \

#define rtcvish_emulator_v1_PauseRequest_CALLBACK NULL
#define rtcvish_emulator_v1_PauseRequest_DEFAULT NULL

#define rtcvish_emulator_v1_PauseResponse_FIELDLIST(X, a) \

#define rtcvish_emulator_v1_PauseResponse_CALLBACK NULL
#define rtcvish_emulator_v1_PauseResponse_DEFAULT NULL

#define rtcvish_emulator_v1_ResumeRequest_FIELDLIST(X, a) \

#define rtcvish_emulator_v1_ResumeRequest_CALLBACK NULL
#define rtcvish_emulator_v1_ResumeRequest_DEFAULT NULL

#define rtcvish_emulator_v1_ResumeResponse_FIELDLIST(X, a) \

#define rtcvish_emulator_v1_ResumeResponse_CALLBACK NULL
#define rtcvish_emulator_v1_ResumeResponse_DEFAULT NULL

#define rtcvish_emulator_v1_StepRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   frames,            1)
#define rtcvish_emulator_v1_StepRequest_CALLBACK NULL
#define rtcvish_emulator_v1_StepRequest_DEFAULT NULL

#define rtcvish_emulator_v1_StepResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   frame,             1)
#define rtcvish_emulator_v1_StepResponse_CALLBACK NULL
#define rtcvish_emulator_v1_StepResponse_DEFAULT NULL

#define rtcvish_emulator_v1_Unit_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   id,                1) \
X(a, POINTER,  SINGULAR, STRING,   domain,            2) \
X(a, STATIC,   SINGULAR, UINT64,   address,           3) \
X(a, STATIC,   SINGULAR, UINT32,   size,              4) \
X(a, POINTER,  ONEOF,    BYTES,    (source,value,source.value),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (source,store,source.store),   6) \
X(a, STATIC,   SINGULAR, SINT64,   tilt,              7) \
X(a, STATIC,   SINGULAR, UINT32,   delay,             8) \
X(a, STATIC,   SINGULAR, UINT32,   lifetime,          9) \
X(a, STATIC,   SINGULAR, BOOL,     loop,             10) \
X(a, STATIC,   SINGULAR, UINT32,   loop_delay,       11) \
X(a, STATIC,   SINGULAR, UENUM,    mode,             12)
#define rtcvish_emulator_v1_Unit_CALLBACK NULL
#define rtcvish_emulator_v1_Unit_DEFAULT NULL
#define rtcvish_emulator_v1_Unit_source_store_MSGTYPE rtcvish_emulator_v1_StoreSource

#define rtcvish_emulator_v1_StoreSource_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, STRING,   domain,            1) \
X(a, STATIC,   SINGULAR, UINT64,   address,           2) \
X(a, STATIC,   SINGULAR, BOOL,     continuous,        3)
#define rtcvish_emulator_v1_StoreSource_CALLBACK NULL
#define rtcvish_emulator_v1_StoreSource_DEFAULT NULL

#define rtcvish_emulator_v1_ApplyUnitsRequest_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  units,             1)
#define rtcvish_emulator_v1_ApplyUnitsRequest_CALLBACK NULL
#define rtcvish_emulator_v1_ApplyUnitsRequest_DEFAULT NULL
#define rtcvish_emulator_v1_ApplyUnitsRequest_units_MSGTYPE rtcvish_emulator_v1_Unit

#define rtcvish_emulator_v1_ApplyUnitsResponse_FIELDLIST(X, a) \

#define rtcvish_emulator_v1_ApplyUnitsResponse_CALLBACK NULL
#define rtcvish_emulator_v1_ApplyUnitsResponse_DEFAULT NULL

#define rtcvish_emulator_v1_RemoveUnitsRequest_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, UINT64,   ids,               1)
#define rtcvish_emulator_v1_RemoveUnitsRequest_CALLBACK NULL
#define rtcvish_emulator_v1_RemoveUnitsRequest_DEFAULT NULL

#define rtcvish_emulator_v1_RemoveUnitsResponse_FIELDLIST(X, a) \

#define rtcvish_emulator_v1_RemoveUnitsResponse_CALLBACK NULL
#define rtcvish_emulator_v1_RemoveUnitsResponse_DEFAULT NULL

#define rtcvish_emulator_v1_ClearUnitsRequest_FIELDLIST(X, a) \

#define rtcvish_emulator_v1_ClearUnitsRequest_CALLBACK NULL
#define rtcvish_emulator_v1_ClearUnitsRequest_DEFAULT NULL

#define rtcvish_emulator_v1_ClearUnitsResponse_FIELDLIST(X, a) \

#define rtcvish_emulator_v1_ClearUnitsResponse_CALLBACK NULL
#define rtcvish_emulator_v1_ClearUnitsResponse_DEFAULT NULL

#define rtcvish_emulator_v1_ListUnitsRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     include_values,    1)
#define rtcvish_emulator_v1_ListUnitsRequest_CALLBACK NULL
#define rtcvish_emulator_v1_ListUnitsRequest_DEFAULT NULL

#define rtcvish_emulator_v1_ListUnitsResponse_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  units,             1)
#define rtcvish_emulator_v1_ListUnitsResponse_CALLBACK NULL
#define rtcvish_emulator_v1_ListUnitsResponse_DEFAULT NULL
#define rtcvish_emulator_v1_ListUnitsResponse_units_MSGTYPE rtcvish_emulator_v1_Unit

#define rtcvish_emulator_v1_SetInputRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   buttons,           1) \
X(a, STATIC,   SINGULAR, BOOL,     touch,             2) \
X(a, STATIC,   SINGULAR, UINT32,   touch_x,           3) \
X(a, STATIC,   SINGULAR, UINT32,   touch_y,           4) \
X(a, STATIC,   SINGULAR, BOOL,     clear,             5)
#define rtcvish_emulator_v1_SetInputRequest_CALLBACK NULL
#define rtcvish_emulator_v1_SetInputRequest_DEFAULT NULL

#define rtcvish_emulator_v1_SetInputResponse_FIELDLIST(X, a) \

#define rtcvish_emulator_v1_SetInputResponse_CALLBACK NULL
#define rtcvish_emulator_v1_SetInputResponse_DEFAULT NULL

#define rtcvish_emulator_v1_Image_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   width,             1) \
X(a, STATIC,   SINGULAR, UINT32,   height,            2) \
X(a, POINTER,  SINGULAR, BYTES,    rgba,              3)
#define rtcvish_emulator_v1_Image_CALLBACK NULL
#define rtcvish_emulator_v1_Image_DEFAULT NULL

#define rtcvish_emulator_v1_ScreenshotRequest_FIELDLIST(X, a) \

#define rtcvish_emulator_v1_ScreenshotRequest_CALLBACK NULL
#define rtcvish_emulator_v1_ScreenshotRequest_DEFAULT NULL

#define rtcvish_emulator_v1_ScreenshotResponse_FIELDLIST(X, a) \
X(a, POINTER,  REPEATED, MESSAGE,  screens,           1)
#define rtcvish_emulator_v1_ScreenshotResponse_CALLBACK NULL
#define rtcvish_emulator_v1_ScreenshotResponse_DEFAULT NULL
#define rtcvish_emulator_v1_ScreenshotResponse_screens_MSGTYPE rtcvish_emulator_v1_Image

#define rtcvish_emulator_v1_SubscribeRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   frame_interval,    1)
#define rtcvish_emulator_v1_SubscribeRequest_CALLBACK NULL
#define rtcvish_emulator_v1_SubscribeRequest_DEFAULT NULL

#define rtcvish_emulator_v1_SubscribeResponse_FIELDLIST(X, a) \

#define rtcvish_emulator_v1_SubscribeResponse_CALLBACK NULL
#define rtcvish_emulator_v1_SubscribeResponse_DEFAULT NULL

#define rtcvish_emulator_v1_PingRequest_FIELDLIST(X, a) \

#define rtcvish_emulator_v1_PingRequest_CALLBACK NULL
#define rtcvish_emulator_v1_PingRequest_DEFAULT NULL

#define rtcvish_emulator_v1_PingResponse_FIELDLIST(X, a) \

#define rtcvish_emulator_v1_PingResponse_CALLBACK NULL
#define rtcvish_emulator_v1_PingResponse_DEFAULT NULL

#define rtcvish_emulator_v1_QuitRequest_FIELDLIST(X, a) \

#define rtcvish_emulator_v1_QuitRequest_CALLBACK NULL
#define rtcvish_emulator_v1_QuitRequest_DEFAULT NULL

#define rtcvish_emulator_v1_QuitResponse_FIELDLIST(X, a) \

#define rtcvish_emulator_v1_QuitResponse_CALLBACK NULL
#define rtcvish_emulator_v1_QuitResponse_DEFAULT NULL

#define rtcvish_emulator_v1_FrameEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   frame,             1)
#define rtcvish_emulator_v1_FrameEvent_CALLBACK NULL
#define rtcvish_emulator_v1_FrameEvent_DEFAULT NULL

#define rtcvish_emulator_v1_StatusEvent_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  status,            1)
#define rtcvish_emulator_v1_StatusEvent_CALLBACK NULL
#define rtcvish_emulator_v1_StatusEvent_DEFAULT NULL
#define rtcvish_emulator_v1_StatusEvent_status_MSGTYPE rtcvish_emulator_v1_Status

extern const pb_msgdesc_t rtcvish_emulator_v1_Message_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_Request_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_Response_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_Event_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_Error_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_HelloRequest_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_HelloResponse_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_Capabilities_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_Status_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_GetStatusRequest_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_GetStatusResponse_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_Domain_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_ListDomainsRequest_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_ListDomainsResponse_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_Range_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_ReadRequest_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_ReadResponse_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_WriteChunk_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_WriteRequest_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_WriteResponse_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_SaveStateRequest_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_SaveStateResponse_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_LoadStateRequest_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_LoadStateResponse_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_LoadRomRequest_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_LoadRomResponse_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_CloseRomRequest_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_CloseRomResponse_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_ResetRequest_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_ResetResponse_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_PauseRequest_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_PauseResponse_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_ResumeRequest_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_ResumeResponse_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_StepRequest_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_StepResponse_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_Unit_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_StoreSource_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_ApplyUnitsRequest_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_ApplyUnitsResponse_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_RemoveUnitsRequest_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_RemoveUnitsResponse_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_ClearUnitsRequest_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_ClearUnitsResponse_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_ListUnitsRequest_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_ListUnitsResponse_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_SetInputRequest_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_SetInputResponse_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_Image_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_ScreenshotRequest_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_ScreenshotResponse_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_SubscribeRequest_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_SubscribeResponse_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_PingRequest_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_PingResponse_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_QuitRequest_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_QuitResponse_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_FrameEvent_msg;
extern const pb_msgdesc_t rtcvish_emulator_v1_StatusEvent_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define rtcvish_emulator_v1_Message_fields &rtcvish_emulator_v1_Message_msg
#define rtcvish_emulator_v1_Request_fields &rtcvish_emulator_v1_Request_msg
#define rtcvish_emulator_v1_Response_fields &rtcvish_emulator_v1_Response_msg
#define rtcvish_emulator_v1_Event_fields &rtcvish_emulator_v1_Event_msg
#define rtcvish_emulator_v1_Error_fields &rtcvish_emulator_v1_Error_msg
#define rtcvish_emulator_v1_HelloRequest_fields &rtcvish_emulator_v1_HelloRequest_msg
#define rtcvish_emulator_v1_HelloResponse_fields &rtcvish_emulator_v1_HelloResponse_msg
#define rtcvish_emulator_v1_Capabilities_fields &rtcvish_emulator_v1_Capabilities_msg
#define rtcvish_emulator_v1_Status_fields &rtcvish_emulator_v1_Status_msg
#define rtcvish_emulator_v1_GetStatusRequest_fields &rtcvish_emulator_v1_GetStatusRequest_msg
#define rtcvish_emulator_v1_GetStatusResponse_fields &rtcvish_emulator_v1_GetStatusResponse_msg
#define rtcvish_emulator_v1_Domain_fields &rtcvish_emulator_v1_Domain_msg
#define rtcvish_emulator_v1_ListDomainsRequest_fields &rtcvish_emulator_v1_ListDomainsRequest_msg
#define rtcvish_emulator_v1_ListDomainsResponse_fields &rtcvish_emulator_v1_ListDomainsResponse_msg
#define rtcvish_emulator_v1_Range_fields &rtcvish_emulator_v1_Range_msg
#define rtcvish_emulator_v1_ReadRequest_fields &rtcvish_emulator_v1_ReadRequest_msg
#define rtcvish_emulator_v1_ReadResponse_fields &rtcvish_emulator_v1_ReadResponse_msg
#define rtcvish_emulator_v1_WriteChunk_fields &rtcvish_emulator_v1_WriteChunk_msg
#define rtcvish_emulator_v1_WriteRequest_fields &rtcvish_emulator_v1_WriteRequest_msg
#define rtcvish_emulator_v1_WriteResponse_fields &rtcvish_emulator_v1_WriteResponse_msg
#define rtcvish_emulator_v1_SaveStateRequest_fields &rtcvish_emulator_v1_SaveStateRequest_msg
#define rtcvish_emulator_v1_SaveStateResponse_fields &rtcvish_emulator_v1_SaveStateResponse_msg
#define rtcvish_emulator_v1_LoadStateRequest_fields &rtcvish_emulator_v1_LoadStateRequest_msg
#define rtcvish_emulator_v1_LoadStateResponse_fields &rtcvish_emulator_v1_LoadStateResponse_msg
#define rtcvish_emulator_v1_LoadRomRequest_fields &rtcvish_emulator_v1_LoadRomRequest_msg
#define rtcvish_emulator_v1_LoadRomResponse_fields &rtcvish_emulator_v1_LoadRomResponse_msg
#define rtcvish_emulator_v1_CloseRomRequest_fields &rtcvish_emulator_v1_CloseRomRequest_msg
#define rtcvish_emulator_v1_CloseRomResponse_fields &rtcvish_emulator_v1_CloseRomResponse_msg
#define rtcvish_emulator_v1_ResetRequest_fields &rtcvish_emulator_v1_ResetRequest_msg
#define rtcvish_emulator_v1_ResetResponse_fields &rtcvish_emulator_v1_ResetResponse_msg
#define rtcvish_emulator_v1_PauseRequest_fields &rtcvish_emulator_v1_PauseRequest_msg
#define rtcvish_emulator_v1_PauseResponse_fields &rtcvish_emulator_v1_PauseResponse_msg
#define rtcvish_emulator_v1_ResumeRequest_fields &rtcvish_emulator_v1_ResumeRequest_msg
#define rtcvish_emulator_v1_ResumeResponse_fields &rtcvish_emulator_v1_ResumeResponse_msg
#define rtcvish_emulator_v1_StepRequest_fields &rtcvish_emulator_v1_StepRequest_msg
#define rtcvish_emulator_v1_StepResponse_fields &rtcvish_emulator_v1_StepResponse_msg
#define rtcvish_emulator_v1_Unit_fields &rtcvish_emulator_v1_Unit_msg
#define rtcvish_emulator_v1_StoreSource_fields &rtcvish_emulator_v1_StoreSource_msg
#define rtcvish_emulator_v1_ApplyUnitsRequest_fields &rtcvish_emulator_v1_ApplyUnitsRequest_msg
#define rtcvish_emulator_v1_ApplyUnitsResponse_fields &rtcvish_emulator_v1_ApplyUnitsResponse_msg
#define rtcvish_emulator_v1_RemoveUnitsRequest_fields &rtcvish_emulator_v1_RemoveUnitsRequest_msg
#define rtcvish_emulator_v1_RemoveUnitsResponse_fields &rtcvish_emulator_v1_RemoveUnitsResponse_msg
#define rtcvish_emulator_v1_ClearUnitsRequest_fields &rtcvish_emulator_v1_ClearUnitsRequest_msg
#define rtcvish_emulator_v1_ClearUnitsResponse_fields &rtcvish_emulator_v1_ClearUnitsResponse_msg
#define rtcvish_emulator_v1_ListUnitsRequest_fields &rtcvish_emulator_v1_ListUnitsRequest_msg
#define rtcvish_emulator_v1_ListUnitsResponse_fields &rtcvish_emulator_v1_ListUnitsResponse_msg
#define rtcvish_emulator_v1_SetInputRequest_fields &rtcvish_emulator_v1_SetInputRequest_msg
#define rtcvish_emulator_v1_SetInputResponse_fields &rtcvish_emulator_v1_SetInputResponse_msg
#define rtcvish_emulator_v1_Image_fields &rtcvish_emulator_v1_Image_msg
#define rtcvish_emulator_v1_ScreenshotRequest_fields &rtcvish_emulator_v1_ScreenshotRequest_msg
#define rtcvish_emulator_v1_ScreenshotResponse_fields &rtcvish_emulator_v1_ScreenshotResponse_msg
#define rtcvish_emulator_v1_SubscribeRequest_fields &rtcvish_emulator_v1_SubscribeRequest_msg
#define rtcvish_emulator_v1_SubscribeResponse_fields &rtcvish_emulator_v1_SubscribeResponse_msg
#define rtcvish_emulator_v1_PingRequest_fields &rtcvish_emulator_v1_PingRequest_msg
#define rtcvish_emulator_v1_PingResponse_fields &rtcvish_emulator_v1_PingResponse_msg
#define rtcvish_emulator_v1_QuitRequest_fields &rtcvish_emulator_v1_QuitRequest_msg
#define rtcvish_emulator_v1_QuitResponse_fields &rtcvish_emulator_v1_QuitResponse_msg
#define rtcvish_emulator_v1_FrameEvent_fields &rtcvish_emulator_v1_FrameEvent_msg
#define rtcvish_emulator_v1_StatusEvent_fields &rtcvish_emulator_v1_StatusEvent_msg

/* Maximum encoded size of messages (where known) */
/* rtcvish_emulator_v1_Message_size depends on runtime parameters */
/* rtcvish_emulator_v1_Request_size depends on runtime parameters */
/* rtcvish_emulator_v1_Response_size depends on runtime parameters */
/* rtcvish_emulator_v1_Event_size depends on runtime parameters */
/* rtcvish_emulator_v1_Error_size depends on runtime parameters */
/* rtcvish_emulator_v1_HelloRequest_size depends on runtime parameters */
/* rtcvish_emulator_v1_HelloResponse_size depends on runtime parameters */
/* rtcvish_emulator_v1_Status_size depends on runtime parameters */
/* rtcvish_emulator_v1_GetStatusResponse_size depends on runtime parameters */
/* rtcvish_emulator_v1_Domain_size depends on runtime parameters */
/* rtcvish_emulator_v1_ListDomainsResponse_size depends on runtime parameters */
/* rtcvish_emulator_v1_Range_size depends on runtime parameters */
/* rtcvish_emulator_v1_ReadRequest_size depends on runtime parameters */
/* rtcvish_emulator_v1_ReadResponse_size depends on runtime parameters */
/* rtcvish_emulator_v1_WriteChunk_size depends on runtime parameters */
/* rtcvish_emulator_v1_WriteRequest_size depends on runtime parameters */
/* rtcvish_emulator_v1_SaveStateResponse_size depends on runtime parameters */
/* rtcvish_emulator_v1_LoadStateRequest_size depends on runtime parameters */
/* rtcvish_emulator_v1_LoadRomRequest_size depends on runtime parameters */
/* rtcvish_emulator_v1_LoadRomResponse_size depends on runtime parameters */
/* rtcvish_emulator_v1_Unit_size depends on runtime parameters */
/* rtcvish_emulator_v1_StoreSource_size depends on runtime parameters */
/* rtcvish_emulator_v1_ApplyUnitsRequest_size depends on runtime parameters */
/* rtcvish_emulator_v1_RemoveUnitsRequest_size depends on runtime parameters */
/* rtcvish_emulator_v1_ListUnitsResponse_size depends on runtime parameters */
/* rtcvish_emulator_v1_Image_size depends on runtime parameters */
/* rtcvish_emulator_v1_ScreenshotResponse_size depends on runtime parameters */
/* rtcvish_emulator_v1_StatusEvent_size depends on runtime parameters */
#define RTCVISH_EMULATOR_V1_EMULATOR_PB_H_MAX_SIZE rtcvish_emulator_v1_SetInputRequest_size
#define rtcvish_emulator_v1_ApplyUnitsResponse_size 0
#define rtcvish_emulator_v1_Capabilities_size    20
#define rtcvish_emulator_v1_ClearUnitsRequest_size 0
#define rtcvish_emulator_v1_ClearUnitsResponse_size 0
#define rtcvish_emulator_v1_CloseRomRequest_size 0
#define rtcvish_emulator_v1_CloseRomResponse_size 0
#define rtcvish_emulator_v1_FrameEvent_size      11
#define rtcvish_emulator_v1_GetStatusRequest_size 0
#define rtcvish_emulator_v1_ListDomainsRequest_size 0
#define rtcvish_emulator_v1_ListUnitsRequest_size 2
#define rtcvish_emulator_v1_LoadStateResponse_size 0
#define rtcvish_emulator_v1_PauseRequest_size    0
#define rtcvish_emulator_v1_PauseResponse_size   0
#define rtcvish_emulator_v1_PingRequest_size     0
#define rtcvish_emulator_v1_PingResponse_size    0
#define rtcvish_emulator_v1_QuitRequest_size     0
#define rtcvish_emulator_v1_QuitResponse_size    0
#define rtcvish_emulator_v1_RemoveUnitsResponse_size 0
#define rtcvish_emulator_v1_ResetRequest_size    0
#define rtcvish_emulator_v1_ResetResponse_size   0
#define rtcvish_emulator_v1_ResumeRequest_size   0
#define rtcvish_emulator_v1_ResumeResponse_size  0
#define rtcvish_emulator_v1_SaveStateRequest_size 0
#define rtcvish_emulator_v1_ScreenshotRequest_size 0
#define rtcvish_emulator_v1_SetInputRequest_size 22
#define rtcvish_emulator_v1_SetInputResponse_size 0
#define rtcvish_emulator_v1_StepRequest_size     6
#define rtcvish_emulator_v1_StepResponse_size    11
#define rtcvish_emulator_v1_SubscribeRequest_size 6
#define rtcvish_emulator_v1_SubscribeResponse_size 0
#define rtcvish_emulator_v1_WriteResponse_size   0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
