/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.2 */

#include "emulator.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(rtcvish_emulator_v1_Message, rtcvish_emulator_v1_Message, AUTO)


PB_BIND(rtcvish_emulator_v1_Request, rtcvish_emulator_v1_Request, AUTO)


PB_BIND(rtcvish_emulator_v1_Response, rtcvish_emulator_v1_Response, AUTO)


PB_BIND(rtcvish_emulator_v1_Event, rtcvish_emulator_v1_Event, AUTO)


PB_BIND(rtcvish_emulator_v1_Error, rtcvish_emulator_v1_Error, AUTO)


PB_BIND(rtcvish_emulator_v1_HelloRequest, rtcvish_emulator_v1_HelloRequest, AUTO)


PB_BIND(rtcvish_emulator_v1_HelloResponse, rtcvish_emulator_v1_HelloResponse, AUTO)


PB_BIND(rtcvish_emulator_v1_Capabilities, rtcvish_emulator_v1_Capabilities, AUTO)


PB_BIND(rtcvish_emulator_v1_Status, rtcvish_emulator_v1_Status, AUTO)


PB_BIND(rtcvish_emulator_v1_GetStatusRequest, rtcvish_emulator_v1_GetStatusRequest, AUTO)


PB_BIND(rtcvish_emulator_v1_GetStatusResponse, rtcvish_emulator_v1_GetStatusResponse, AUTO)


PB_BIND(rtcvish_emulator_v1_Domain, rtcvish_emulator_v1_Domain, AUTO)


PB_BIND(rtcvish_emulator_v1_ListDomainsRequest, rtcvish_emulator_v1_ListDomainsRequest, AUTO)


PB_BIND(rtcvish_emulator_v1_ListDomainsResponse, rtcvish_emulator_v1_ListDomainsResponse, AUTO)


PB_BIND(rtcvish_emulator_v1_Range, rtcvish_emulator_v1_Range, AUTO)


PB_BIND(rtcvish_emulator_v1_ReadRequest, rtcvish_emulator_v1_ReadRequest, AUTO)


PB_BIND(rtcvish_emulator_v1_ReadResponse, rtcvish_emulator_v1_ReadResponse, AUTO)


PB_BIND(rtcvish_emulator_v1_WriteChunk, rtcvish_emulator_v1_WriteChunk, AUTO)


PB_BIND(rtcvish_emulator_v1_WriteRequest, rtcvish_emulator_v1_WriteRequest, AUTO)


PB_BIND(rtcvish_emulator_v1_WriteResponse, rtcvish_emulator_v1_WriteResponse, AUTO)


PB_BIND(rtcvish_emulator_v1_SaveStateRequest, rtcvish_emulator_v1_SaveStateRequest, AUTO)


PB_BIND(rtcvish_emulator_v1_SaveStateResponse, rtcvish_emulator_v1_SaveStateResponse, AUTO)


PB_BIND(rtcvish_emulator_v1_LoadStateRequest, rtcvish_emulator_v1_LoadStateRequest, AUTO)


PB_BIND(rtcvish_emulator_v1_LoadStateResponse, rtcvish_emulator_v1_LoadStateResponse, AUTO)


PB_BIND(rtcvish_emulator_v1_LoadRomRequest, rtcvish_emulator_v1_LoadRomRequest, AUTO)


PB_BIND(rtcvish_emulator_v1_LoadRomResponse, rtcvish_emulator_v1_LoadRomResponse, AUTO)


PB_BIND(rtcvish_emulator_v1_CloseRomRequest, rtcvish_emulator_v1_CloseRomRequest, AUTO)


PB_BIND(rtcvish_emulator_v1_CloseRomResponse, rtcvish_emulator_v1_CloseRomResponse, AUTO)


PB_BIND(rtcvish_emulator_v1_ResetRequest, rtcvish_emulator_v1_ResetRequest, AUTO)


PB_BIND(rtcvish_emulator_v1_ResetResponse, rtcvish_emulator_v1_ResetResponse, AUTO)


PB_BIND(rtcvish_emulator_v1_PauseRequest, rtcvish_emulator_v1_PauseRequest, AUTO)


PB_BIND(rtcvish_emulator_v1_PauseResponse, rtcvish_emulator_v1_PauseResponse, AUTO)


PB_BIND(rtcvish_emulator_v1_ResumeRequest, rtcvish_emulator_v1_ResumeRequest, AUTO)


PB_BIND(rtcvish_emulator_v1_ResumeResponse, rtcvish_emulator_v1_ResumeResponse, AUTO)


PB_BIND(rtcvish_emulator_v1_StepRequest, rtcvish_emulator_v1_StepRequest, AUTO)


PB_BIND(rtcvish_emulator_v1_StepResponse, rtcvish_emulator_v1_StepResponse, AUTO)


PB_BIND(rtcvish_emulator_v1_Unit, rtcvish_emulator_v1_Unit, AUTO)


PB_BIND(rtcvish_emulator_v1_StoreSource, rtcvish_emulator_v1_StoreSource, AUTO)


PB_BIND(rtcvish_emulator_v1_ApplyUnitsRequest, rtcvish_emulator_v1_ApplyUnitsRequest, AUTO)


PB_BIND(rtcvish_emulator_v1_ApplyUnitsResponse, rtcvish_emulator_v1_ApplyUnitsResponse, AUTO)


PB_BIND(rtcvish_emulator_v1_RemoveUnitsRequest, rtcvish_emulator_v1_RemoveUnitsRequest, AUTO)


PB_BIND(rtcvish_emulator_v1_RemoveUnitsResponse, rtcvish_emulator_v1_RemoveUnitsResponse, AUTO)


PB_BIND(rtcvish_emulator_v1_ClearUnitsRequest, rtcvish_emulator_v1_ClearUnitsRequest, AUTO)


PB_BIND(rtcvish_emulator_v1_ClearUnitsResponse, rtcvish_emulator_v1_ClearUnitsResponse, AUTO)


PB_BIND(rtcvish_emulator_v1_ListUnitsRequest, rtcvish_emulator_v1_ListUnitsRequest, AUTO)


PB_BIND(rtcvish_emulator_v1_ListUnitsResponse, rtcvish_emulator_v1_ListUnitsResponse, AUTO)


PB_BIND(rtcvish_emulator_v1_SetInputRequest, rtcvish_emulator_v1_SetInputRequest, AUTO)


PB_BIND(rtcvish_emulator_v1_SetInputResponse, rtcvish_emulator_v1_SetInputResponse, AUTO)


PB_BIND(rtcvish_emulator_v1_Image, rtcvish_emulator_v1_Image, AUTO)


PB_BIND(rtcvish_emulator_v1_ScreenshotRequest, rtcvish_emulator_v1_ScreenshotRequest, AUTO)


PB_BIND(rtcvish_emulator_v1_ScreenshotResponse, rtcvish_emulator_v1_ScreenshotResponse, AUTO)


PB_BIND(rtcvish_emulator_v1_SubscribeRequest, rtcvish_emulator_v1_SubscribeRequest, AUTO)


PB_BIND(rtcvish_emulator_v1_SubscribeResponse, rtcvish_emulator_v1_SubscribeResponse, AUTO)


PB_BIND(rtcvish_emulator_v1_PingRequest, rtcvish_emulator_v1_PingRequest, AUTO)


PB_BIND(rtcvish_emulator_v1_PingResponse, rtcvish_emulator_v1_PingResponse, AUTO)


PB_BIND(rtcvish_emulator_v1_QuitRequest, rtcvish_emulator_v1_QuitRequest, AUTO)


PB_BIND(rtcvish_emulator_v1_QuitResponse, rtcvish_emulator_v1_QuitResponse, AUTO)


PB_BIND(rtcvish_emulator_v1_FrameEvent, rtcvish_emulator_v1_FrameEvent, AUTO)


PB_BIND(rtcvish_emulator_v1_StatusEvent, rtcvish_emulator_v1_StatusEvent, AUTO)







